// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package relation

import (
	"douyin/kitex_gen/user"
	"fmt"
)

type RelationActionRequest struct {
	UserId     int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ToUserId   int64 `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
	ActionType int32 `thrift:"action_type,3" frugal:"3,default,i32" json:"action_type"`
}

func NewRelationActionRequest() *RelationActionRequest {
	return &RelationActionRequest{}
}

func (p *RelationActionRequest) InitDefault() {
}

func (p *RelationActionRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *RelationActionRequest) GetToUserId() (v int64) {
	return p.ToUserId
}

func (p *RelationActionRequest) GetActionType() (v int32) {
	return p.ActionType
}
func (p *RelationActionRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *RelationActionRequest) SetToUserId(val int64) {
	p.ToUserId = val
}
func (p *RelationActionRequest) SetActionType(val int32) {
	p.ActionType = val
}

func (p *RelationActionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RelationActionRequest(%+v)", *p)
}

var fieldIDToName_RelationActionRequest = map[int16]string{
	1: "user_id",
	2: "to_user_id",
	3: "action_type",
}

type RelationActionResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
}

func NewRelationActionResponse() *RelationActionResponse {
	return &RelationActionResponse{}
}

func (p *RelationActionResponse) InitDefault() {
}

func (p *RelationActionResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *RelationActionResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}
func (p *RelationActionResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *RelationActionResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}

func (p *RelationActionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RelationActionResponse(%+v)", *p)
}

var fieldIDToName_RelationActionResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
}

type FollowListRequest struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ToUserId int64 `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
}

func NewFollowListRequest() *FollowListRequest {
	return &FollowListRequest{}
}

func (p *FollowListRequest) InitDefault() {
}

func (p *FollowListRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *FollowListRequest) GetToUserId() (v int64) {
	return p.ToUserId
}
func (p *FollowListRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *FollowListRequest) SetToUserId(val int64) {
	p.ToUserId = val
}

func (p *FollowListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowListRequest(%+v)", *p)
}

var fieldIDToName_FollowListRequest = map[int16]string{
	1: "user_id",
	2: "to_user_id",
}

type FollowListResponse struct {
	StatusCode int32        `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string       `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	UserList   []*user.User `thrift:"user_list,3" frugal:"3,default,list<user.User>" json:"user_list"`
}

func NewFollowListResponse() *FollowListResponse {
	return &FollowListResponse{}
}

func (p *FollowListResponse) InitDefault() {
}

func (p *FollowListResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *FollowListResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *FollowListResponse) GetUserList() (v []*user.User) {
	return p.UserList
}
func (p *FollowListResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *FollowListResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *FollowListResponse) SetUserList(val []*user.User) {
	p.UserList = val
}

func (p *FollowListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowListResponse(%+v)", *p)
}

var fieldIDToName_FollowListResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "user_list",
}

type FollowerListRequest struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ToUserId int64 `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
}

func NewFollowerListRequest() *FollowerListRequest {
	return &FollowerListRequest{}
}

func (p *FollowerListRequest) InitDefault() {
}

func (p *FollowerListRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *FollowerListRequest) GetToUserId() (v int64) {
	return p.ToUserId
}
func (p *FollowerListRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *FollowerListRequest) SetToUserId(val int64) {
	p.ToUserId = val
}

func (p *FollowerListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowerListRequest(%+v)", *p)
}

var fieldIDToName_FollowerListRequest = map[int16]string{
	1: "user_id",
	2: "to_user_id",
}

type FollowerListResponse struct {
	StatusCode int32        `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string       `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	UserList   []*user.User `thrift:"user_list,3" frugal:"3,default,list<user.User>" json:"user_list"`
}

func NewFollowerListResponse() *FollowerListResponse {
	return &FollowerListResponse{}
}

func (p *FollowerListResponse) InitDefault() {
}

func (p *FollowerListResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *FollowerListResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *FollowerListResponse) GetUserList() (v []*user.User) {
	return p.UserList
}
func (p *FollowerListResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *FollowerListResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *FollowerListResponse) SetUserList(val []*user.User) {
	p.UserList = val
}

func (p *FollowerListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowerListResponse(%+v)", *p)
}

var fieldIDToName_FollowerListResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "user_list",
}

type FollowListCountResponse struct {
	Count int32 `thrift:"count,1" frugal:"1,default,i32" json:"count"`
}

func NewFollowListCountResponse() *FollowListCountResponse {
	return &FollowListCountResponse{}
}

func (p *FollowListCountResponse) InitDefault() {
}

func (p *FollowListCountResponse) GetCount() (v int32) {
	return p.Count
}
func (p *FollowListCountResponse) SetCount(val int32) {
	p.Count = val
}

func (p *FollowListCountResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowListCountResponse(%+v)", *p)
}

var fieldIDToName_FollowListCountResponse = map[int16]string{
	1: "count",
}

type FollowerListCountRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewFollowerListCountRequest() *FollowerListCountRequest {
	return &FollowerListCountRequest{}
}

func (p *FollowerListCountRequest) InitDefault() {
}

func (p *FollowerListCountRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *FollowerListCountRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *FollowerListCountRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowerListCountRequest(%+v)", *p)
}

var fieldIDToName_FollowerListCountRequest = map[int16]string{
	1: "user_id",
}

type FriendListRequest struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ToUserId int64 `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
}

func NewFriendListRequest() *FriendListRequest {
	return &FriendListRequest{}
}

func (p *FriendListRequest) InitDefault() {
}

func (p *FriendListRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *FriendListRequest) GetToUserId() (v int64) {
	return p.ToUserId
}
func (p *FriendListRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *FriendListRequest) SetToUserId(val int64) {
	p.ToUserId = val
}

func (p *FriendListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendListRequest(%+v)", *p)
}

var fieldIDToName_FriendListRequest = map[int16]string{
	1: "user_id",
	2: "to_user_id",
}

type FriendListResponse struct {
	StatusCode int32        `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string       `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	UserList   []*user.User `thrift:"user_list,3" frugal:"3,default,list<user.User>" json:"user_list"`
}

func NewFriendListResponse() *FriendListResponse {
	return &FriendListResponse{}
}

func (p *FriendListResponse) InitDefault() {
}

func (p *FriendListResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *FriendListResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *FriendListResponse) GetUserList() (v []*user.User) {
	return p.UserList
}
func (p *FriendListResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *FriendListResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *FriendListResponse) SetUserList(val []*user.User) {
	p.UserList = val
}

func (p *FriendListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendListResponse(%+v)", *p)
}

var fieldIDToName_FriendListResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "user_list",
}

type IsFollowingRequest struct {
	ActorId int64 `thrift:"actor_id,1" frugal:"1,default,i64" json:"actor_id"`
	UserId  int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewIsFollowingRequest() *IsFollowingRequest {
	return &IsFollowingRequest{}
}

func (p *IsFollowingRequest) InitDefault() {
}

func (p *IsFollowingRequest) GetActorId() (v int64) {
	return p.ActorId
}

func (p *IsFollowingRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *IsFollowingRequest) SetActorId(val int64) {
	p.ActorId = val
}
func (p *IsFollowingRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *IsFollowingRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IsFollowingRequest(%+v)", *p)
}

var fieldIDToName_IsFollowingRequest = map[int16]string{
	1: "actor_id",
	2: "user_id",
}

type IsFriendRequest struct {
	ActorId int64 `thrift:"actor_id,1" frugal:"1,default,i64" json:"actor_id"`
	UserId  int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewIsFriendRequest() *IsFriendRequest {
	return &IsFriendRequest{}
}

func (p *IsFriendRequest) InitDefault() {
}

func (p *IsFriendRequest) GetActorId() (v int64) {
	return p.ActorId
}

func (p *IsFriendRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *IsFriendRequest) SetActorId(val int64) {
	p.ActorId = val
}
func (p *IsFriendRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *IsFriendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IsFriendRequest(%+v)", *p)
}

var fieldIDToName_IsFriendRequest = map[int16]string{
	1: "actor_id",
	2: "user_id",
}
