// Code generated by Kitex v0.16.3. DO NOT EDIT.

package videoappservice

import (
	"context"
	comment "douyin/kitex_gen/comment"
	favorite "douyin/kitex_gen/favorite"
	video "douyin/kitex_gen/video"
	videoapp "douyin/kitex_gen/videoapp"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"VideoFeed": kitex.NewMethodInfo(
		videoFeedHandler,
		newVideoAppServiceVideoFeedArgs,
		newVideoAppServiceVideoFeedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PublishVideo": kitex.NewMethodInfo(
		publishVideoHandler,
		newVideoAppServicePublishVideoArgs,
		newVideoAppServicePublishVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPublishVideoList": kitex.NewMethodInfo(
		getPublishVideoListHandler,
		newVideoAppServiceGetPublishVideoListArgs,
		newVideoAppServiceGetPublishVideoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetWorkCount": kitex.NewMethodInfo(
		getWorkCountHandler,
		newVideoAppServiceGetWorkCountArgs,
		newVideoAppServiceGetWorkCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommentAction": kitex.NewMethodInfo(
		commentActionHandler,
		newVideoAppServiceCommentActionArgs,
		newVideoAppServiceCommentActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCommentList": kitex.NewMethodInfo(
		getCommentListHandler,
		newVideoAppServiceGetCommentListArgs,
		newVideoAppServiceGetCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCommentCount": kitex.NewMethodInfo(
		getCommentCountHandler,
		newVideoAppServiceGetCommentCountArgs,
		newVideoAppServiceGetCommentCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FavoriteAction": kitex.NewMethodInfo(
		favoriteActionHandler,
		newVideoAppServiceFavoriteActionArgs,
		newVideoAppServiceFavoriteActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFavoriteList": kitex.NewMethodInfo(
		getFavoriteListHandler,
		newVideoAppServiceGetFavoriteListArgs,
		newVideoAppServiceGetFavoriteListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetVideoFavoriteCount": kitex.NewMethodInfo(
		getVideoFavoriteCountHandler,
		newVideoAppServiceGetVideoFavoriteCountArgs,
		newVideoAppServiceGetVideoFavoriteCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserFavoriteCount": kitex.NewMethodInfo(
		getUserFavoriteCountHandler,
		newVideoAppServiceGetUserFavoriteCountArgs,
		newVideoAppServiceGetUserFavoriteCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserTotalFavoritedCount": kitex.NewMethodInfo(
		getUserTotalFavoritedCountHandler,
		newVideoAppServiceGetUserTotalFavoritedCountArgs,
		newVideoAppServiceGetUserTotalFavoritedCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IsUserFavorite": kitex.NewMethodInfo(
		isUserFavoriteHandler,
		newVideoAppServiceIsUserFavoriteArgs,
		newVideoAppServiceIsUserFavoriteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoAppServiceServiceInfo                = NewServiceInfo()
	videoAppServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoAppServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoAppServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoAppServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoAppServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoAppService"
	handlerType := (*videoapp.VideoAppService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "videoapp",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func videoFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceVideoFeedArgs)
	realResult := result.(*videoapp.VideoAppServiceVideoFeedResult)
	success, err := handler.(videoapp.VideoAppService).VideoFeed(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoAppServiceVideoFeedArgs() interface{} {
	return videoapp.NewVideoAppServiceVideoFeedArgs()
}

func newVideoAppServiceVideoFeedResult() interface{} {
	return videoapp.NewVideoAppServiceVideoFeedResult()
}

func publishVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServicePublishVideoArgs)
	realResult := result.(*videoapp.VideoAppServicePublishVideoResult)
	success, err := handler.(videoapp.VideoAppService).PublishVideo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoAppServicePublishVideoArgs() interface{} {
	return videoapp.NewVideoAppServicePublishVideoArgs()
}

func newVideoAppServicePublishVideoResult() interface{} {
	return videoapp.NewVideoAppServicePublishVideoResult()
}

func getPublishVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetPublishVideoListArgs)
	realResult := result.(*videoapp.VideoAppServiceGetPublishVideoListResult)
	success, err := handler.(videoapp.VideoAppService).GetPublishVideoList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoAppServiceGetPublishVideoListArgs() interface{} {
	return videoapp.NewVideoAppServiceGetPublishVideoListArgs()
}

func newVideoAppServiceGetPublishVideoListResult() interface{} {
	return videoapp.NewVideoAppServiceGetPublishVideoListResult()
}

func getWorkCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetWorkCountArgs)
	realResult := result.(*videoapp.VideoAppServiceGetWorkCountResult)
	success, err := handler.(videoapp.VideoAppService).GetWorkCount(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVideoAppServiceGetWorkCountArgs() interface{} {
	return videoapp.NewVideoAppServiceGetWorkCountArgs()
}

func newVideoAppServiceGetWorkCountResult() interface{} {
	return videoapp.NewVideoAppServiceGetWorkCountResult()
}

func commentActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceCommentActionArgs)
	realResult := result.(*videoapp.VideoAppServiceCommentActionResult)
	success, err := handler.(videoapp.VideoAppService).CommentAction(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoAppServiceCommentActionArgs() interface{} {
	return videoapp.NewVideoAppServiceCommentActionArgs()
}

func newVideoAppServiceCommentActionResult() interface{} {
	return videoapp.NewVideoAppServiceCommentActionResult()
}

func getCommentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetCommentListArgs)
	realResult := result.(*videoapp.VideoAppServiceGetCommentListResult)
	success, err := handler.(videoapp.VideoAppService).GetCommentList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoAppServiceGetCommentListArgs() interface{} {
	return videoapp.NewVideoAppServiceGetCommentListArgs()
}

func newVideoAppServiceGetCommentListResult() interface{} {
	return videoapp.NewVideoAppServiceGetCommentListResult()
}

func getCommentCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetCommentCountArgs)
	realResult := result.(*videoapp.VideoAppServiceGetCommentCountResult)
	success, err := handler.(videoapp.VideoAppService).GetCommentCount(ctx, realArg.VideoId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVideoAppServiceGetCommentCountArgs() interface{} {
	return videoapp.NewVideoAppServiceGetCommentCountArgs()
}

func newVideoAppServiceGetCommentCountResult() interface{} {
	return videoapp.NewVideoAppServiceGetCommentCountResult()
}

func favoriteActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceFavoriteActionArgs)
	realResult := result.(*videoapp.VideoAppServiceFavoriteActionResult)
	success, err := handler.(videoapp.VideoAppService).FavoriteAction(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoAppServiceFavoriteActionArgs() interface{} {
	return videoapp.NewVideoAppServiceFavoriteActionArgs()
}

func newVideoAppServiceFavoriteActionResult() interface{} {
	return videoapp.NewVideoAppServiceFavoriteActionResult()
}

func getFavoriteListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetFavoriteListArgs)
	realResult := result.(*videoapp.VideoAppServiceGetFavoriteListResult)
	success, err := handler.(videoapp.VideoAppService).GetFavoriteList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoAppServiceGetFavoriteListArgs() interface{} {
	return videoapp.NewVideoAppServiceGetFavoriteListArgs()
}

func newVideoAppServiceGetFavoriteListResult() interface{} {
	return videoapp.NewVideoAppServiceGetFavoriteListResult()
}

func getVideoFavoriteCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetVideoFavoriteCountArgs)
	realResult := result.(*videoapp.VideoAppServiceGetVideoFavoriteCountResult)
	success, err := handler.(videoapp.VideoAppService).GetVideoFavoriteCount(ctx, realArg.VideoId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVideoAppServiceGetVideoFavoriteCountArgs() interface{} {
	return videoapp.NewVideoAppServiceGetVideoFavoriteCountArgs()
}

func newVideoAppServiceGetVideoFavoriteCountResult() interface{} {
	return videoapp.NewVideoAppServiceGetVideoFavoriteCountResult()
}

func getUserFavoriteCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetUserFavoriteCountArgs)
	realResult := result.(*videoapp.VideoAppServiceGetUserFavoriteCountResult)
	success, err := handler.(videoapp.VideoAppService).GetUserFavoriteCount(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVideoAppServiceGetUserFavoriteCountArgs() interface{} {
	return videoapp.NewVideoAppServiceGetUserFavoriteCountArgs()
}

func newVideoAppServiceGetUserFavoriteCountResult() interface{} {
	return videoapp.NewVideoAppServiceGetUserFavoriteCountResult()
}

func getUserTotalFavoritedCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceGetUserTotalFavoritedCountArgs)
	realResult := result.(*videoapp.VideoAppServiceGetUserTotalFavoritedCountResult)
	success, err := handler.(videoapp.VideoAppService).GetUserTotalFavoritedCount(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVideoAppServiceGetUserTotalFavoritedCountArgs() interface{} {
	return videoapp.NewVideoAppServiceGetUserTotalFavoritedCountArgs()
}

func newVideoAppServiceGetUserTotalFavoritedCountResult() interface{} {
	return videoapp.NewVideoAppServiceGetUserTotalFavoritedCountResult()
}

func isUserFavoriteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoapp.VideoAppServiceIsUserFavoriteArgs)
	realResult := result.(*videoapp.VideoAppServiceIsUserFavoriteResult)
	success, err := handler.(videoapp.VideoAppService).IsUserFavorite(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVideoAppServiceIsUserFavoriteArgs() interface{} {
	return videoapp.NewVideoAppServiceIsUserFavoriteArgs()
}

func newVideoAppServiceIsUserFavoriteResult() interface{} {
	return videoapp.NewVideoAppServiceIsUserFavoriteResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) VideoFeed(ctx context.Context, request *video.VideoFeedRequest) (r *video.VideoFeedResponse, err error) {
	var _args videoapp.VideoAppServiceVideoFeedArgs
	_args.Request = request
	var _result videoapp.VideoAppServiceVideoFeedResult
	if err = p.c.Call(ctx, "VideoFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishVideo(ctx context.Context, request *video.PublishVideoRequest) (r *video.PublishVideoResponse, err error) {
	var _args videoapp.VideoAppServicePublishVideoArgs
	_args.Request = request
	var _result videoapp.VideoAppServicePublishVideoResult
	if err = p.c.Call(ctx, "PublishVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPublishVideoList(ctx context.Context, request *video.PublishVideoListRequest) (r *video.PublishVideoListResponse, err error) {
	var _args videoapp.VideoAppServiceGetPublishVideoListArgs
	_args.Request = request
	var _result videoapp.VideoAppServiceGetPublishVideoListResult
	if err = p.c.Call(ctx, "GetPublishVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetWorkCount(ctx context.Context, userId int64) (r int32, err error) {
	var _args videoapp.VideoAppServiceGetWorkCountArgs
	_args.UserId = userId
	var _result videoapp.VideoAppServiceGetWorkCountResult
	if err = p.c.Call(ctx, "GetWorkCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentAction(ctx context.Context, request *comment.CommentActionRequest) (r *comment.CommentActionResponse, err error) {
	var _args videoapp.VideoAppServiceCommentActionArgs
	_args.Request = request
	var _result videoapp.VideoAppServiceCommentActionResult
	if err = p.c.Call(ctx, "CommentAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentList(ctx context.Context, request *comment.CommentListRequest) (r *comment.CommentListResponse, err error) {
	var _args videoapp.VideoAppServiceGetCommentListArgs
	_args.Request = request
	var _result videoapp.VideoAppServiceGetCommentListResult
	if err = p.c.Call(ctx, "GetCommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentCount(ctx context.Context, videoId int64) (r int32, err error) {
	var _args videoapp.VideoAppServiceGetCommentCountArgs
	_args.VideoId = videoId
	var _result videoapp.VideoAppServiceGetCommentCountResult
	if err = p.c.Call(ctx, "GetCommentCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteAction(ctx context.Context, request *favorite.FavoriteActionRequest) (r *favorite.FavoriteActionResponse, err error) {
	var _args videoapp.VideoAppServiceFavoriteActionArgs
	_args.Request = request
	var _result videoapp.VideoAppServiceFavoriteActionResult
	if err = p.c.Call(ctx, "FavoriteAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFavoriteList(ctx context.Context, request *favorite.FavoriteListRequest) (r *favorite.FavoriteListResponse, err error) {
	var _args videoapp.VideoAppServiceGetFavoriteListArgs
	_args.Request = request
	var _result videoapp.VideoAppServiceGetFavoriteListResult
	if err = p.c.Call(ctx, "GetFavoriteList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoFavoriteCount(ctx context.Context, videoId int64) (r int32, err error) {
	var _args videoapp.VideoAppServiceGetVideoFavoriteCountArgs
	_args.VideoId = videoId
	var _result videoapp.VideoAppServiceGetVideoFavoriteCountResult
	if err = p.c.Call(ctx, "GetVideoFavoriteCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserFavoriteCount(ctx context.Context, userId int64) (r int32, err error) {
	var _args videoapp.VideoAppServiceGetUserFavoriteCountArgs
	_args.UserId = userId
	var _result videoapp.VideoAppServiceGetUserFavoriteCountResult
	if err = p.c.Call(ctx, "GetUserFavoriteCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserTotalFavoritedCount(ctx context.Context, userId int64) (r int32, err error) {
	var _args videoapp.VideoAppServiceGetUserTotalFavoritedCountArgs
	_args.UserId = userId
	var _result videoapp.VideoAppServiceGetUserTotalFavoritedCountResult
	if err = p.c.Call(ctx, "GetUserTotalFavoritedCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsUserFavorite(ctx context.Context, request *favorite.IsUserFavoriteRequest) (r bool, err error) {
	var _args videoapp.VideoAppServiceIsUserFavoriteArgs
	_args.Request = request
	var _result videoapp.VideoAppServiceIsUserFavoriteResult
	if err = p.c.Call(ctx, "IsUserFavorite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
