// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package message

import (
	"context"
	"fmt"
)

type Message struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	ToUserId   int64  `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
	FromUserId int64  `thrift:"from_user_id,3" frugal:"3,default,i64" json:"from_user_id"`
	Content    string `thrift:"content,4" frugal:"4,default,string" json:"content"`
	CreateTime int64  `thrift:"create_time,5" frugal:"5,default,i64" json:"create_time"`
}

func NewMessage() *Message {
	return &Message{}
}

func (p *Message) InitDefault() {
}

func (p *Message) GetId() (v int64) {
	return p.Id
}

func (p *Message) GetToUserId() (v int64) {
	return p.ToUserId
}

func (p *Message) GetFromUserId() (v int64) {
	return p.FromUserId
}

func (p *Message) GetContent() (v string) {
	return p.Content
}

func (p *Message) GetCreateTime() (v int64) {
	return p.CreateTime
}
func (p *Message) SetId(val int64) {
	p.Id = val
}
func (p *Message) SetToUserId(val int64) {
	p.ToUserId = val
}
func (p *Message) SetFromUserId(val int64) {
	p.FromUserId = val
}
func (p *Message) SetContent(val string) {
	p.Content = val
}
func (p *Message) SetCreateTime(val int64) {
	p.CreateTime = val
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

var fieldIDToName_Message = map[int16]string{
	1: "id",
	2: "to_user_id",
	3: "from_user_id",
	4: "content",
	5: "create_time",
}

type MessageChatRequest struct {
	FromUserId int64 `thrift:"from_user_id,1" frugal:"1,default,i64" json:"from_user_id"`
	ToUserId   int64 `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
	PreMsgTime int64 `thrift:"pre_msg_time,3" frugal:"3,default,i64" json:"pre_msg_time"`
}

func NewMessageChatRequest() *MessageChatRequest {
	return &MessageChatRequest{}
}

func (p *MessageChatRequest) InitDefault() {
}

func (p *MessageChatRequest) GetFromUserId() (v int64) {
	return p.FromUserId
}

func (p *MessageChatRequest) GetToUserId() (v int64) {
	return p.ToUserId
}

func (p *MessageChatRequest) GetPreMsgTime() (v int64) {
	return p.PreMsgTime
}
func (p *MessageChatRequest) SetFromUserId(val int64) {
	p.FromUserId = val
}
func (p *MessageChatRequest) SetToUserId(val int64) {
	p.ToUserId = val
}
func (p *MessageChatRequest) SetPreMsgTime(val int64) {
	p.PreMsgTime = val
}

func (p *MessageChatRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageChatRequest(%+v)", *p)
}

var fieldIDToName_MessageChatRequest = map[int16]string{
	1: "from_user_id",
	2: "to_user_id",
	3: "pre_msg_time",
}

type MessageChatResponse struct {
	StatusCode  int32      `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg   string     `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	MessageList []*Message `thrift:"message_list,3" frugal:"3,default,list<Message>" json:"message_list"`
}

func NewMessageChatResponse() *MessageChatResponse {
	return &MessageChatResponse{}
}

func (p *MessageChatResponse) InitDefault() {
}

func (p *MessageChatResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *MessageChatResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *MessageChatResponse) GetMessageList() (v []*Message) {
	return p.MessageList
}
func (p *MessageChatResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *MessageChatResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *MessageChatResponse) SetMessageList(val []*Message) {
	p.MessageList = val
}

func (p *MessageChatResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageChatResponse(%+v)", *p)
}

var fieldIDToName_MessageChatResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "message_list",
}

type MessageActionRequest struct {
	FromUserId int64  `thrift:"from_user_id,1" frugal:"1,default,i64" json:"from_user_id"`
	ToUserId   int64  `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
	ActionType int32  `thrift:"action_type,3" frugal:"3,default,i32" json:"action_type"`
	Content    string `thrift:"content,4" frugal:"4,default,string" json:"content"`
}

func NewMessageActionRequest() *MessageActionRequest {
	return &MessageActionRequest{}
}

func (p *MessageActionRequest) InitDefault() {
}

func (p *MessageActionRequest) GetFromUserId() (v int64) {
	return p.FromUserId
}

func (p *MessageActionRequest) GetToUserId() (v int64) {
	return p.ToUserId
}

func (p *MessageActionRequest) GetActionType() (v int32) {
	return p.ActionType
}

func (p *MessageActionRequest) GetContent() (v string) {
	return p.Content
}
func (p *MessageActionRequest) SetFromUserId(val int64) {
	p.FromUserId = val
}
func (p *MessageActionRequest) SetToUserId(val int64) {
	p.ToUserId = val
}
func (p *MessageActionRequest) SetActionType(val int32) {
	p.ActionType = val
}
func (p *MessageActionRequest) SetContent(val string) {
	p.Content = val
}

func (p *MessageActionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageActionRequest(%+v)", *p)
}

var fieldIDToName_MessageActionRequest = map[int16]string{
	1: "from_user_id",
	2: "to_user_id",
	3: "action_type",
	4: "content",
}

type MessageActionResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
}

func NewMessageActionResponse() *MessageActionResponse {
	return &MessageActionResponse{}
}

func (p *MessageActionResponse) InitDefault() {
}

func (p *MessageActionResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *MessageActionResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}
func (p *MessageActionResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *MessageActionResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}

func (p *MessageActionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageActionResponse(%+v)", *p)
}

var fieldIDToName_MessageActionResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
}

type MessageService interface {
	MessageChat(ctx context.Context, request *MessageChatRequest) (r *MessageChatResponse, err error)

	MessageAction(ctx context.Context, request *MessageActionRequest) (r *MessageActionResponse, err error)
}

type MessageServiceMessageChatArgs struct {
	Request *MessageChatRequest `thrift:"Request,1" frugal:"1,default,MessageChatRequest" json:"Request"`
}

func NewMessageServiceMessageChatArgs() *MessageServiceMessageChatArgs {
	return &MessageServiceMessageChatArgs{}
}

func (p *MessageServiceMessageChatArgs) InitDefault() {
}

var MessageServiceMessageChatArgs_Request_DEFAULT *MessageChatRequest

func (p *MessageServiceMessageChatArgs) GetRequest() (v *MessageChatRequest) {
	if !p.IsSetRequest() {
		return MessageServiceMessageChatArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MessageServiceMessageChatArgs) SetRequest(val *MessageChatRequest) {
	p.Request = val
}

func (p *MessageServiceMessageChatArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MessageServiceMessageChatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageServiceMessageChatArgs(%+v)", *p)
}

var fieldIDToName_MessageServiceMessageChatArgs = map[int16]string{
	1: "Request",
}

type MessageServiceMessageChatResult struct {
	Success *MessageChatResponse `thrift:"success,0,optional" frugal:"0,optional,MessageChatResponse" json:"success,omitempty"`
}

func NewMessageServiceMessageChatResult() *MessageServiceMessageChatResult {
	return &MessageServiceMessageChatResult{}
}

func (p *MessageServiceMessageChatResult) InitDefault() {
}

var MessageServiceMessageChatResult_Success_DEFAULT *MessageChatResponse

func (p *MessageServiceMessageChatResult) GetSuccess() (v *MessageChatResponse) {
	if !p.IsSetSuccess() {
		return MessageServiceMessageChatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MessageServiceMessageChatResult) SetSuccess(x interface{}) {
	p.Success = x.(*MessageChatResponse)
}

func (p *MessageServiceMessageChatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MessageServiceMessageChatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageServiceMessageChatResult(%+v)", *p)
}

var fieldIDToName_MessageServiceMessageChatResult = map[int16]string{
	0: "success",
}

type MessageServiceMessageActionArgs struct {
	Request *MessageActionRequest `thrift:"Request,1" frugal:"1,default,MessageActionRequest" json:"Request"`
}

func NewMessageServiceMessageActionArgs() *MessageServiceMessageActionArgs {
	return &MessageServiceMessageActionArgs{}
}

func (p *MessageServiceMessageActionArgs) InitDefault() {
}

var MessageServiceMessageActionArgs_Request_DEFAULT *MessageActionRequest

func (p *MessageServiceMessageActionArgs) GetRequest() (v *MessageActionRequest) {
	if !p.IsSetRequest() {
		return MessageServiceMessageActionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MessageServiceMessageActionArgs) SetRequest(val *MessageActionRequest) {
	p.Request = val
}

func (p *MessageServiceMessageActionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MessageServiceMessageActionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageServiceMessageActionArgs(%+v)", *p)
}

var fieldIDToName_MessageServiceMessageActionArgs = map[int16]string{
	1: "Request",
}

type MessageServiceMessageActionResult struct {
	Success *MessageActionResponse `thrift:"success,0,optional" frugal:"0,optional,MessageActionResponse" json:"success,omitempty"`
}

func NewMessageServiceMessageActionResult() *MessageServiceMessageActionResult {
	return &MessageServiceMessageActionResult{}
}

func (p *MessageServiceMessageActionResult) InitDefault() {
}

var MessageServiceMessageActionResult_Success_DEFAULT *MessageActionResponse

func (p *MessageServiceMessageActionResult) GetSuccess() (v *MessageActionResponse) {
	if !p.IsSetSuccess() {
		return MessageServiceMessageActionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MessageServiceMessageActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*MessageActionResponse)
}

func (p *MessageServiceMessageActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MessageServiceMessageActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageServiceMessageActionResult(%+v)", *p)
}

var fieldIDToName_MessageServiceMessageActionResult = map[int16]string{
	0: "success",
}
