// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package video

import (
	"douyin/kitex_gen/user"
	"fmt"
)

type Video struct {
	Id            int64      `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Author        *user.User `thrift:"author,2" frugal:"2,default,user.User" json:"author"`
	PlayUrl       string     `thrift:"play_url,3" frugal:"3,default,string" json:"play_url"`
	CoverUrl      string     `thrift:"cover_url,4" frugal:"4,default,string" json:"cover_url"`
	FavoriteCount int32      `thrift:"favorite_count,5" frugal:"5,default,i32" json:"favorite_count"`
	CommentCount  int32      `thrift:"comment_count,6" frugal:"6,default,i32" json:"comment_count"`
	IsFavorite    bool       `thrift:"is_favorite,7" frugal:"7,default,bool" json:"is_favorite"`
	Title         string     `thrift:"title,8" frugal:"8,default,string" json:"title"`
}

func NewVideo() *Video {
	return &Video{}
}

func (p *Video) InitDefault() {
}

func (p *Video) GetId() (v int64) {
	return p.Id
}

var Video_Author_DEFAULT *user.User

func (p *Video) GetAuthor() (v *user.User) {
	if !p.IsSetAuthor() {
		return Video_Author_DEFAULT
	}
	return p.Author
}

func (p *Video) GetPlayUrl() (v string) {
	return p.PlayUrl
}

func (p *Video) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *Video) GetFavoriteCount() (v int32) {
	return p.FavoriteCount
}

func (p *Video) GetCommentCount() (v int32) {
	return p.CommentCount
}

func (p *Video) GetIsFavorite() (v bool) {
	return p.IsFavorite
}

func (p *Video) GetTitle() (v string) {
	return p.Title
}
func (p *Video) SetId(val int64) {
	p.Id = val
}
func (p *Video) SetAuthor(val *user.User) {
	p.Author = val
}
func (p *Video) SetPlayUrl(val string) {
	p.PlayUrl = val
}
func (p *Video) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *Video) SetFavoriteCount(val int32) {
	p.FavoriteCount = val
}
func (p *Video) SetCommentCount(val int32) {
	p.CommentCount = val
}
func (p *Video) SetIsFavorite(val bool) {
	p.IsFavorite = val
}
func (p *Video) SetTitle(val string) {
	p.Title = val
}

func (p *Video) IsSetAuthor() bool {
	return p.Author != nil
}

func (p *Video) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Video(%+v)", *p)
}

var fieldIDToName_Video = map[int16]string{
	1: "id",
	2: "author",
	3: "play_url",
	4: "cover_url",
	5: "favorite_count",
	6: "comment_count",
	7: "is_favorite",
	8: "title",
}

type VideoFeedRequest struct {
	LatestTime *string `thrift:"latest_time,1,optional" frugal:"1,optional,string" json:"latest_time,omitempty"`
	UserId     int64   `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewVideoFeedRequest() *VideoFeedRequest {
	return &VideoFeedRequest{}
}

func (p *VideoFeedRequest) InitDefault() {
}

var VideoFeedRequest_LatestTime_DEFAULT string

func (p *VideoFeedRequest) GetLatestTime() (v string) {
	if !p.IsSetLatestTime() {
		return VideoFeedRequest_LatestTime_DEFAULT
	}
	return *p.LatestTime
}

func (p *VideoFeedRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *VideoFeedRequest) SetLatestTime(val *string) {
	p.LatestTime = val
}
func (p *VideoFeedRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *VideoFeedRequest) IsSetLatestTime() bool {
	return p.LatestTime != nil
}

func (p *VideoFeedRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoFeedRequest(%+v)", *p)
}

var fieldIDToName_VideoFeedRequest = map[int16]string{
	1: "latest_time",
	2: "user_id",
}

type VideoFeedResponse struct {
	StatusCode int32    `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string   `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	VideoList  []*Video `thrift:"video_list,3" frugal:"3,default,list<Video>" json:"video_list"`
	NextTime   int64    `thrift:"next_time,4" frugal:"4,default,i64" json:"next_time"`
}

func NewVideoFeedResponse() *VideoFeedResponse {
	return &VideoFeedResponse{}
}

func (p *VideoFeedResponse) InitDefault() {
}

func (p *VideoFeedResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *VideoFeedResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *VideoFeedResponse) GetVideoList() (v []*Video) {
	return p.VideoList
}

func (p *VideoFeedResponse) GetNextTime() (v int64) {
	return p.NextTime
}
func (p *VideoFeedResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *VideoFeedResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *VideoFeedResponse) SetVideoList(val []*Video) {
	p.VideoList = val
}
func (p *VideoFeedResponse) SetNextTime(val int64) {
	p.NextTime = val
}

func (p *VideoFeedResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoFeedResponse(%+v)", *p)
}

var fieldIDToName_VideoFeedResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "video_list",
	4: "next_time",
}

type PublishVideoRequest struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Data   []byte `thrift:"data,2" frugal:"2,default,binary" json:"data"`
	Title  string `thrift:"title,3" frugal:"3,default,string" json:"title"`
}

func NewPublishVideoRequest() *PublishVideoRequest {
	return &PublishVideoRequest{}
}

func (p *PublishVideoRequest) InitDefault() {
}

func (p *PublishVideoRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *PublishVideoRequest) GetData() (v []byte) {
	return p.Data
}

func (p *PublishVideoRequest) GetTitle() (v string) {
	return p.Title
}
func (p *PublishVideoRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *PublishVideoRequest) SetData(val []byte) {
	p.Data = val
}
func (p *PublishVideoRequest) SetTitle(val string) {
	p.Title = val
}

func (p *PublishVideoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoRequest(%+v)", *p)
}

var fieldIDToName_PublishVideoRequest = map[int16]string{
	1: "user_id",
	2: "data",
	3: "title",
}

type PublishVideoResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
}

func NewPublishVideoResponse() *PublishVideoResponse {
	return &PublishVideoResponse{}
}

func (p *PublishVideoResponse) InitDefault() {
}

func (p *PublishVideoResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *PublishVideoResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}
func (p *PublishVideoResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *PublishVideoResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}

func (p *PublishVideoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoResponse(%+v)", *p)
}

var fieldIDToName_PublishVideoResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
}

type PublishVideoListRequest struct {
	FromUserId int64 `thrift:"from_user_id,1" frugal:"1,default,i64" json:"from_user_id"`
	ToUserId   int64 `thrift:"to_user_id,2" frugal:"2,default,i64" json:"to_user_id"`
}

func NewPublishVideoListRequest() *PublishVideoListRequest {
	return &PublishVideoListRequest{}
}

func (p *PublishVideoListRequest) InitDefault() {
}

func (p *PublishVideoListRequest) GetFromUserId() (v int64) {
	return p.FromUserId
}

func (p *PublishVideoListRequest) GetToUserId() (v int64) {
	return p.ToUserId
}
func (p *PublishVideoListRequest) SetFromUserId(val int64) {
	p.FromUserId = val
}
func (p *PublishVideoListRequest) SetToUserId(val int64) {
	p.ToUserId = val
}

func (p *PublishVideoListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoListRequest(%+v)", *p)
}

var fieldIDToName_PublishVideoListRequest = map[int16]string{
	1: "from_user_id",
	2: "to_user_id",
}

type PublishVideoListResponse struct {
	StatusCode int32    `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string   `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	VideoList  []*Video `thrift:"video_list,3" frugal:"3,default,list<Video>" json:"video_list"`
}

func NewPublishVideoListResponse() *PublishVideoListResponse {
	return &PublishVideoListResponse{}
}

func (p *PublishVideoListResponse) InitDefault() {
}

func (p *PublishVideoListResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *PublishVideoListResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *PublishVideoListResponse) GetVideoList() (v []*Video) {
	return p.VideoList
}
func (p *PublishVideoListResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *PublishVideoListResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *PublishVideoListResponse) SetVideoList(val []*Video) {
	p.VideoList = val
}

func (p *PublishVideoListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoListResponse(%+v)", *p)
}

var fieldIDToName_PublishVideoListResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "video_list",
}

type GetWorkCountRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetWorkCountRequest() *GetWorkCountRequest {
	return &GetWorkCountRequest{}
}

func (p *GetWorkCountRequest) InitDefault() {
}

func (p *GetWorkCountRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetWorkCountRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetWorkCountRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetWorkCountRequest(%+v)", *p)
}

var fieldIDToName_GetWorkCountRequest = map[int16]string{
	1: "user_id",
}

type GetWorkCountResponse struct {
	WorkCount int32 `thrift:"work_count,1" frugal:"1,default,i32" json:"work_count"`
}

func NewGetWorkCountResponse() *GetWorkCountResponse {
	return &GetWorkCountResponse{}
}

func (p *GetWorkCountResponse) InitDefault() {
}

func (p *GetWorkCountResponse) GetWorkCount() (v int32) {
	return p.WorkCount
}
func (p *GetWorkCountResponse) SetWorkCount(val int32) {
	p.WorkCount = val
}

func (p *GetWorkCountResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetWorkCountResponse(%+v)", *p)
}

var fieldIDToName_GetWorkCountResponse = map[int16]string{
	1: "work_count",
}
