// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package comment

import (
	"douyin/kitex_gen/user"
	"fmt"
)

type Comment struct {
	Id         int64      `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	User       *user.User `thrift:"user,2" frugal:"2,default,user.User" json:"user"`
	Content    string     `thrift:"content,3" frugal:"3,default,string" json:"content"`
	CreateDate string     `thrift:"create_date,4" frugal:"4,default,string" json:"create_date"`
}

func NewComment() *Comment {
	return &Comment{}
}

func (p *Comment) InitDefault() {
}

func (p *Comment) GetId() (v int64) {
	return p.Id
}

var Comment_User_DEFAULT *user.User

func (p *Comment) GetUser() (v *user.User) {
	if !p.IsSetUser() {
		return Comment_User_DEFAULT
	}
	return p.User
}

func (p *Comment) GetContent() (v string) {
	return p.Content
}

func (p *Comment) GetCreateDate() (v string) {
	return p.CreateDate
}
func (p *Comment) SetId(val int64) {
	p.Id = val
}
func (p *Comment) SetUser(val *user.User) {
	p.User = val
}
func (p *Comment) SetContent(val string) {
	p.Content = val
}
func (p *Comment) SetCreateDate(val string) {
	p.CreateDate = val
}

func (p *Comment) IsSetUser() bool {
	return p.User != nil
}

func (p *Comment) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Comment(%+v)", *p)
}

var fieldIDToName_Comment = map[int16]string{
	1: "id",
	2: "user",
	3: "content",
	4: "create_date",
}

type CommentActionRequest struct {
	UserId      int64   `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	VideoId     int64   `thrift:"video_id,2" frugal:"2,default,i64" json:"video_id"`
	ActionType  int32   `thrift:"action_type,3" frugal:"3,default,i32" json:"action_type"`
	CommentText *string `thrift:"comment_text,4,optional" frugal:"4,optional,string" json:"comment_text,omitempty"`
	CommentId   *int64  `thrift:"comment_id,5,optional" frugal:"5,optional,i64" json:"comment_id,omitempty"`
}

func NewCommentActionRequest() *CommentActionRequest {
	return &CommentActionRequest{}
}

func (p *CommentActionRequest) InitDefault() {
}

func (p *CommentActionRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CommentActionRequest) GetVideoId() (v int64) {
	return p.VideoId
}

func (p *CommentActionRequest) GetActionType() (v int32) {
	return p.ActionType
}

var CommentActionRequest_CommentText_DEFAULT string

func (p *CommentActionRequest) GetCommentText() (v string) {
	if !p.IsSetCommentText() {
		return CommentActionRequest_CommentText_DEFAULT
	}
	return *p.CommentText
}

var CommentActionRequest_CommentId_DEFAULT int64

func (p *CommentActionRequest) GetCommentId() (v int64) {
	if !p.IsSetCommentId() {
		return CommentActionRequest_CommentId_DEFAULT
	}
	return *p.CommentId
}
func (p *CommentActionRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CommentActionRequest) SetVideoId(val int64) {
	p.VideoId = val
}
func (p *CommentActionRequest) SetActionType(val int32) {
	p.ActionType = val
}
func (p *CommentActionRequest) SetCommentText(val *string) {
	p.CommentText = val
}
func (p *CommentActionRequest) SetCommentId(val *int64) {
	p.CommentId = val
}

func (p *CommentActionRequest) IsSetCommentText() bool {
	return p.CommentText != nil
}

func (p *CommentActionRequest) IsSetCommentId() bool {
	return p.CommentId != nil
}

func (p *CommentActionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentActionRequest(%+v)", *p)
}

var fieldIDToName_CommentActionRequest = map[int16]string{
	1: "user_id",
	2: "video_id",
	3: "action_type",
	4: "comment_text",
	5: "comment_id",
}

type CommentActionResponse struct {
	StatusCode int32    `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string   `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	Comment    *Comment `thrift:"comment,3,optional" frugal:"3,optional,Comment" json:"comment,omitempty"`
}

func NewCommentActionResponse() *CommentActionResponse {
	return &CommentActionResponse{}
}

func (p *CommentActionResponse) InitDefault() {
}

func (p *CommentActionResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *CommentActionResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

var CommentActionResponse_Comment_DEFAULT *Comment

func (p *CommentActionResponse) GetComment() (v *Comment) {
	if !p.IsSetComment() {
		return CommentActionResponse_Comment_DEFAULT
	}
	return p.Comment
}
func (p *CommentActionResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *CommentActionResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *CommentActionResponse) SetComment(val *Comment) {
	p.Comment = val
}

func (p *CommentActionResponse) IsSetComment() bool {
	return p.Comment != nil
}

func (p *CommentActionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentActionResponse(%+v)", *p)
}

var fieldIDToName_CommentActionResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "comment",
}

type CommentListRequest struct {
	UserId  int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	VideoId int64 `thrift:"video_id,2" frugal:"2,default,i64" json:"video_id"`
}

func NewCommentListRequest() *CommentListRequest {
	return &CommentListRequest{}
}

func (p *CommentListRequest) InitDefault() {
}

func (p *CommentListRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CommentListRequest) GetVideoId() (v int64) {
	return p.VideoId
}
func (p *CommentListRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CommentListRequest) SetVideoId(val int64) {
	p.VideoId = val
}

func (p *CommentListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentListRequest(%+v)", *p)
}

var fieldIDToName_CommentListRequest = map[int16]string{
	1: "user_id",
	2: "video_id",
}

type CommentListResponse struct {
	StatusCode  int32      `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg   string     `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	CommentList []*Comment `thrift:"comment_list,3" frugal:"3,default,list<Comment>" json:"comment_list"`
}

func NewCommentListResponse() *CommentListResponse {
	return &CommentListResponse{}
}

func (p *CommentListResponse) InitDefault() {
}

func (p *CommentListResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *CommentListResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *CommentListResponse) GetCommentList() (v []*Comment) {
	return p.CommentList
}
func (p *CommentListResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *CommentListResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *CommentListResponse) SetCommentList(val []*Comment) {
	p.CommentList = val
}

func (p *CommentListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentListResponse(%+v)", *p)
}

var fieldIDToName_CommentListResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "comment_list",
}
