name: "douyin"
mode: "local"
port: 8080
version: "v0.0.1"
local:
  mysql:
    username: root
    password: 12345678
    address: "127.0.0.1"
    port: 3306
    database: douyin
    timeout: 10
  redis:
    address: "127.0.0.1"
    port: 6379
    password: ""
    vcid_db: 0          # vedioId 到 commentId 的一对多映射, commentId 存放在zset中
    cvid_db: 1          # commentId 到 vedioId 的一对一映射
    cid_comment_db: 2   # commentId 到 comment 的一对一映射
    pool_size: 30
    min_idle_conns: 30
remote:
  mysql:
    username: root
    password: "a1253767085"
    address: "127.0.0.1"
    port: 3306
    database: douyin
    timeout: 10
  redis:
    address: "172.27.161.27"
    port: 6379
    password: ""
    vcid_db: 0          # vedioId 到 commentId 的一对多映射, commentId 存放在zset中
    cvid_db: 1          # commentId 到 vedioId 的一对一映射
    cid_comment_db: 2   # commentId 到 comment 的一对一映射
    pool_size: 30
    min_idle_conns: 30