name: "douyin"
node: 1
mode: "remote"
port: 8080
version: "v0.0.1"
log:
  level: "debug"
  filename: "./log/douyin.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5
local:
  mysql:
    address: "127.0.0.1"
    port: 3306
    username: doushen
    password: doushen
    database: doushen
    timeout: 10
  redis:
    address: "127.0.0.1"
    port: 6379
    password: "fl#ztS6g0F9O"
    comment_db: 0
    pool_size: 30
    min_idle_conns: 30
    expire_time: 1800   # 30分钟
  kafka:
    address: "127.0.0.1"
    port: 9092
  mongo:
    address: "127.0.0.1"
    port: 27017
    username: admin
    password: w5W7PNXYBzLBGHRx
    db: admin

remote:
  mysql:
    address: "127.0.0.1"
    port: 3306
    username: doushen
    password: CEzYXnXpGcx5rZwW
    database: doushen
    timeout: 10
  redis:
    address: "127.0.0.1"
    port: 6379
    password: "fl#ztS6g0F9O"
    comment_db: 0
    pool_size: 30
    min_idle_conns: 30
    expire_time: 1800   # 30分钟
  kafka:
    address: "127.0.0.1"
    port: 9092
  mongo:
    address: "127.0.0.1"
    port: 27017
    username: admin
    password: w5W7PNXYBzLBGHRx
    db: admin