name: "douyin"
mode: "local"
port: 8080
version: "v0.0.1"
local:
  mysql:
    username: root
    password: 12345678
    address: "127.0.0.1"
    port: 3306
    database: douyin
    timeout: 10
  redis:
    address: "127.0.0.1"
    port: 6379
    password: ""
    db: 0
    ufvdb: 1
    vfudb: 2
    pool_size: 30
    min_idle_conns: 30
remote:
  mysql:
    username: root
    password: oYhkEnSG
    address: 172.16.32.102
    port: 50819
    database: douyin
    timeout: 10