Local:
  Mysql:
    username: root
    password: mysql
    address: 127.0.0.1
    port: 3306
    database: douyin
    timeout: 10
  Redis:
    addr: "127.0.0.1:6379"
    password: ""
    DB: 0
    poolSize: 30
    minIdleConn: 30
Remote:
  Mysql:
    username: root
    password: oYhkEnSG
    address: 172.16.32.102
    port: 50819
    database: douyin
    timeout: 10
oss:
  tencent: "https://douyin-1319971229.cos.ap-nanjing.myqcloud.com"
