// Code generated by Kitex v0.16.3. DO NOT EDIT.

package socialservice

import (
	"context"
	relation "douyin/kitex_gen/relation"
	social "douyin/kitex_gen/social"
	user "douyin/kitex_gen/user"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newSocialServiceRegisterArgs,
		newSocialServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newSocialServiceLoginArgs,
		newSocialServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfoById": kitex.NewMethodInfo(
		getUserInfoByIdHandler,
		newSocialServiceGetUserInfoByIdArgs,
		newSocialServiceGetUserInfoByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RelationAction": kitex.NewMethodInfo(
		relationActionHandler,
		newSocialServiceRelationActionArgs,
		newSocialServiceRelationActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFollowList": kitex.NewMethodInfo(
		getFollowListHandler,
		newSocialServiceGetFollowListArgs,
		newSocialServiceGetFollowListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFollowerList": kitex.NewMethodInfo(
		getFollowerListHandler,
		newSocialServiceGetFollowerListArgs,
		newSocialServiceGetFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendList": kitex.NewMethodInfo(
		getFriendListHandler,
		newSocialServiceGetFriendListArgs,
		newSocialServiceGetFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFollowListCount": kitex.NewMethodInfo(
		getFollowListCountHandler,
		newSocialServiceGetFollowListCountArgs,
		newSocialServiceGetFollowListCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFollowerListCount": kitex.NewMethodInfo(
		getFollowerListCountHandler,
		newSocialServiceGetFollowerListCountArgs,
		newSocialServiceGetFollowerListCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IsFollowing": kitex.NewMethodInfo(
		isFollowingHandler,
		newSocialServiceIsFollowingArgs,
		newSocialServiceIsFollowingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IsFriend": kitex.NewMethodInfo(
		isFriendHandler,
		newSocialServiceIsFriendArgs,
		newSocialServiceIsFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	socialServiceServiceInfo                = NewServiceInfo()
	socialServiceServiceInfoForClient       = NewServiceInfoForClient()
	socialServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return socialServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return socialServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return socialServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SocialService"
	handlerType := (*social.SocialService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "social",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceRegisterArgs)
	realResult := result.(*social.SocialServiceRegisterResult)
	success, err := handler.(social.SocialService).Register(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialServiceRegisterArgs() interface{} {
	return social.NewSocialServiceRegisterArgs()
}

func newSocialServiceRegisterResult() interface{} {
	return social.NewSocialServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceLoginArgs)
	realResult := result.(*social.SocialServiceLoginResult)
	success, err := handler.(social.SocialService).Login(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialServiceLoginArgs() interface{} {
	return social.NewSocialServiceLoginArgs()
}

func newSocialServiceLoginResult() interface{} {
	return social.NewSocialServiceLoginResult()
}

func getUserInfoByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceGetUserInfoByIdArgs)
	realResult := result.(*social.SocialServiceGetUserInfoByIdResult)
	success, err := handler.(social.SocialService).GetUserInfoById(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialServiceGetUserInfoByIdArgs() interface{} {
	return social.NewSocialServiceGetUserInfoByIdArgs()
}

func newSocialServiceGetUserInfoByIdResult() interface{} {
	return social.NewSocialServiceGetUserInfoByIdResult()
}

func relationActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceRelationActionArgs)
	realResult := result.(*social.SocialServiceRelationActionResult)
	success, err := handler.(social.SocialService).RelationAction(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialServiceRelationActionArgs() interface{} {
	return social.NewSocialServiceRelationActionArgs()
}

func newSocialServiceRelationActionResult() interface{} {
	return social.NewSocialServiceRelationActionResult()
}

func getFollowListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceGetFollowListArgs)
	realResult := result.(*social.SocialServiceGetFollowListResult)
	success, err := handler.(social.SocialService).GetFollowList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialServiceGetFollowListArgs() interface{} {
	return social.NewSocialServiceGetFollowListArgs()
}

func newSocialServiceGetFollowListResult() interface{} {
	return social.NewSocialServiceGetFollowListResult()
}

func getFollowerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceGetFollowerListArgs)
	realResult := result.(*social.SocialServiceGetFollowerListResult)
	success, err := handler.(social.SocialService).GetFollowerList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialServiceGetFollowerListArgs() interface{} {
	return social.NewSocialServiceGetFollowerListArgs()
}

func newSocialServiceGetFollowerListResult() interface{} {
	return social.NewSocialServiceGetFollowerListResult()
}

func getFriendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceGetFriendListArgs)
	realResult := result.(*social.SocialServiceGetFriendListResult)
	success, err := handler.(social.SocialService).GetFriendList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSocialServiceGetFriendListArgs() interface{} {
	return social.NewSocialServiceGetFriendListArgs()
}

func newSocialServiceGetFriendListResult() interface{} {
	return social.NewSocialServiceGetFriendListResult()
}

func getFollowListCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceGetFollowListCountArgs)
	realResult := result.(*social.SocialServiceGetFollowListCountResult)
	success, err := handler.(social.SocialService).GetFollowListCount(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newSocialServiceGetFollowListCountArgs() interface{} {
	return social.NewSocialServiceGetFollowListCountArgs()
}

func newSocialServiceGetFollowListCountResult() interface{} {
	return social.NewSocialServiceGetFollowListCountResult()
}

func getFollowerListCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceGetFollowerListCountArgs)
	realResult := result.(*social.SocialServiceGetFollowerListCountResult)
	success, err := handler.(social.SocialService).GetFollowerListCount(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newSocialServiceGetFollowerListCountArgs() interface{} {
	return social.NewSocialServiceGetFollowerListCountArgs()
}

func newSocialServiceGetFollowerListCountResult() interface{} {
	return social.NewSocialServiceGetFollowerListCountResult()
}

func isFollowingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceIsFollowingArgs)
	realResult := result.(*social.SocialServiceIsFollowingResult)
	success, err := handler.(social.SocialService).IsFollowing(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newSocialServiceIsFollowingArgs() interface{} {
	return social.NewSocialServiceIsFollowingArgs()
}

func newSocialServiceIsFollowingResult() interface{} {
	return social.NewSocialServiceIsFollowingResult()
}

func isFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*social.SocialServiceIsFriendArgs)
	realResult := result.(*social.SocialServiceIsFriendResult)
	success, err := handler.(social.SocialService).IsFriend(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newSocialServiceIsFriendArgs() interface{} {
	return social.NewSocialServiceIsFriendArgs()
}

func newSocialServiceIsFriendResult() interface{} {
	return social.NewSocialServiceIsFriendResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, request *user.UserRegisterRequest) (r *user.UserRegisterResponse, err error) {
	var _args social.SocialServiceRegisterArgs
	_args.Request = request
	var _result social.SocialServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, request *user.UserLoginRequest) (r *user.UserLoginResponse, err error) {
	var _args social.SocialServiceLoginArgs
	_args.Request = request
	var _result social.SocialServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfoById(ctx context.Context, request *user.UserInfoByIdRequest) (r *user.UserInfoByIdResponse, err error) {
	var _args social.SocialServiceGetUserInfoByIdArgs
	_args.Request = request
	var _result social.SocialServiceGetUserInfoByIdResult
	if err = p.c.Call(ctx, "GetUserInfoById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RelationAction(ctx context.Context, request *relation.RelationActionRequest) (r *relation.RelationActionResponse, err error) {
	var _args social.SocialServiceRelationActionArgs
	_args.Request = request
	var _result social.SocialServiceRelationActionResult
	if err = p.c.Call(ctx, "RelationAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFollowList(ctx context.Context, request *relation.FollowListRequest) (r *relation.FollowListResponse, err error) {
	var _args social.SocialServiceGetFollowListArgs
	_args.Request = request
	var _result social.SocialServiceGetFollowListResult
	if err = p.c.Call(ctx, "GetFollowList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFollowerList(ctx context.Context, request *relation.FollowerListRequest) (r *relation.FollowerListResponse, err error) {
	var _args social.SocialServiceGetFollowerListArgs
	_args.Request = request
	var _result social.SocialServiceGetFollowerListResult
	if err = p.c.Call(ctx, "GetFollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendList(ctx context.Context, request *relation.FriendListRequest) (r *relation.FriendListResponse, err error) {
	var _args social.SocialServiceGetFriendListArgs
	_args.Request = request
	var _result social.SocialServiceGetFriendListResult
	if err = p.c.Call(ctx, "GetFriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFollowListCount(ctx context.Context, userId int64) (r int32, err error) {
	var _args social.SocialServiceGetFollowListCountArgs
	_args.UserId = userId
	var _result social.SocialServiceGetFollowListCountResult
	if err = p.c.Call(ctx, "GetFollowListCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFollowerListCount(ctx context.Context, userId int64) (r int32, err error) {
	var _args social.SocialServiceGetFollowerListCountArgs
	_args.UserId = userId
	var _result social.SocialServiceGetFollowerListCountResult
	if err = p.c.Call(ctx, "GetFollowerListCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsFollowing(ctx context.Context, request *relation.IsFollowingRequest) (r bool, err error) {
	var _args social.SocialServiceIsFollowingArgs
	_args.Request = request
	var _result social.SocialServiceIsFollowingResult
	if err = p.c.Call(ctx, "IsFollowing", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsFriend(ctx context.Context, request *relation.IsFriendRequest) (r bool, err error) {
	var _args social.SocialServiceIsFriendArgs
	_args.Request = request
	var _result social.SocialServiceIsFriendResult
	if err = p.c.Call(ctx, "IsFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
