// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package social

import (
	"context"
	"douyin/kitex_gen/relation"
	"douyin/kitex_gen/user"
	"fmt"
)

type SocialService interface {
	Register(ctx context.Context, request *user.UserRegisterRequest) (r *user.UserRegisterResponse, err error)

	Login(ctx context.Context, request *user.UserLoginRequest) (r *user.UserLoginResponse, err error)

	GetUserInfoById(ctx context.Context, request *user.UserInfoByIdRequest) (r *user.UserInfoByIdResponse, err error)

	RelationAction(ctx context.Context, request *relation.RelationActionRequest) (r *relation.RelationActionResponse, err error)

	GetFollowList(ctx context.Context, request *relation.FollowListRequest) (r *relation.FollowListResponse, err error)

	GetFollowerList(ctx context.Context, request *relation.FollowerListRequest) (r *relation.FollowerListResponse, err error)

	GetFriendList(ctx context.Context, request *relation.FriendListRequest) (r *relation.FriendListResponse, err error)

	GetFollowListCount(ctx context.Context, userId int64) (r int32, err error)

	GetFollowerListCount(ctx context.Context, userId int64) (r int32, err error)

	IsFollowing(ctx context.Context, request *relation.IsFollowingRequest) (r bool, err error)

	IsFriend(ctx context.Context, request *relation.IsFriendRequest) (r bool, err error)
}

type SocialServiceRegisterArgs struct {
	Request *user.UserRegisterRequest `thrift:"Request,1" frugal:"1,default,user.UserRegisterRequest" json:"Request"`
}

func NewSocialServiceRegisterArgs() *SocialServiceRegisterArgs {
	return &SocialServiceRegisterArgs{}
}

func (p *SocialServiceRegisterArgs) InitDefault() {
}

var SocialServiceRegisterArgs_Request_DEFAULT *user.UserRegisterRequest

func (p *SocialServiceRegisterArgs) GetRequest() (v *user.UserRegisterRequest) {
	if !p.IsSetRequest() {
		return SocialServiceRegisterArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceRegisterArgs) SetRequest(val *user.UserRegisterRequest) {
	p.Request = val
}

func (p *SocialServiceRegisterArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceRegisterArgs = map[int16]string{
	1: "Request",
}

type SocialServiceRegisterResult struct {
	Success *user.UserRegisterResponse `thrift:"success,0,optional" frugal:"0,optional,user.UserRegisterResponse" json:"success,omitempty"`
}

func NewSocialServiceRegisterResult() *SocialServiceRegisterResult {
	return &SocialServiceRegisterResult{}
}

func (p *SocialServiceRegisterResult) InitDefault() {
}

var SocialServiceRegisterResult_Success_DEFAULT *user.UserRegisterResponse

func (p *SocialServiceRegisterResult) GetSuccess() (v *user.UserRegisterResponse) {
	if !p.IsSetSuccess() {
		return SocialServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UserRegisterResponse)
}

func (p *SocialServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_SocialServiceRegisterResult = map[int16]string{
	0: "success",
}

type SocialServiceLoginArgs struct {
	Request *user.UserLoginRequest `thrift:"Request,1" frugal:"1,default,user.UserLoginRequest" json:"Request"`
}

func NewSocialServiceLoginArgs() *SocialServiceLoginArgs {
	return &SocialServiceLoginArgs{}
}

func (p *SocialServiceLoginArgs) InitDefault() {
}

var SocialServiceLoginArgs_Request_DEFAULT *user.UserLoginRequest

func (p *SocialServiceLoginArgs) GetRequest() (v *user.UserLoginRequest) {
	if !p.IsSetRequest() {
		return SocialServiceLoginArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceLoginArgs) SetRequest(val *user.UserLoginRequest) {
	p.Request = val
}

func (p *SocialServiceLoginArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceLoginArgs = map[int16]string{
	1: "Request",
}

type SocialServiceLoginResult struct {
	Success *user.UserLoginResponse `thrift:"success,0,optional" frugal:"0,optional,user.UserLoginResponse" json:"success,omitempty"`
}

func NewSocialServiceLoginResult() *SocialServiceLoginResult {
	return &SocialServiceLoginResult{}
}

func (p *SocialServiceLoginResult) InitDefault() {
}

var SocialServiceLoginResult_Success_DEFAULT *user.UserLoginResponse

func (p *SocialServiceLoginResult) GetSuccess() (v *user.UserLoginResponse) {
	if !p.IsSetSuccess() {
		return SocialServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UserLoginResponse)
}

func (p *SocialServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceLoginResult(%+v)", *p)
}

var fieldIDToName_SocialServiceLoginResult = map[int16]string{
	0: "success",
}

type SocialServiceGetUserInfoByIdArgs struct {
	Request *user.UserInfoByIdRequest `thrift:"Request,1" frugal:"1,default,user.UserInfoByIdRequest" json:"Request"`
}

func NewSocialServiceGetUserInfoByIdArgs() *SocialServiceGetUserInfoByIdArgs {
	return &SocialServiceGetUserInfoByIdArgs{}
}

func (p *SocialServiceGetUserInfoByIdArgs) InitDefault() {
}

var SocialServiceGetUserInfoByIdArgs_Request_DEFAULT *user.UserInfoByIdRequest

func (p *SocialServiceGetUserInfoByIdArgs) GetRequest() (v *user.UserInfoByIdRequest) {
	if !p.IsSetRequest() {
		return SocialServiceGetUserInfoByIdArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceGetUserInfoByIdArgs) SetRequest(val *user.UserInfoByIdRequest) {
	p.Request = val
}

func (p *SocialServiceGetUserInfoByIdArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceGetUserInfoByIdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetUserInfoByIdArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetUserInfoByIdArgs = map[int16]string{
	1: "Request",
}

type SocialServiceGetUserInfoByIdResult struct {
	Success *user.UserInfoByIdResponse `thrift:"success,0,optional" frugal:"0,optional,user.UserInfoByIdResponse" json:"success,omitempty"`
}

func NewSocialServiceGetUserInfoByIdResult() *SocialServiceGetUserInfoByIdResult {
	return &SocialServiceGetUserInfoByIdResult{}
}

func (p *SocialServiceGetUserInfoByIdResult) InitDefault() {
}

var SocialServiceGetUserInfoByIdResult_Success_DEFAULT *user.UserInfoByIdResponse

func (p *SocialServiceGetUserInfoByIdResult) GetSuccess() (v *user.UserInfoByIdResponse) {
	if !p.IsSetSuccess() {
		return SocialServiceGetUserInfoByIdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetUserInfoByIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UserInfoByIdResponse)
}

func (p *SocialServiceGetUserInfoByIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetUserInfoByIdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetUserInfoByIdResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetUserInfoByIdResult = map[int16]string{
	0: "success",
}

type SocialServiceRelationActionArgs struct {
	Request *relation.RelationActionRequest `thrift:"Request,1" frugal:"1,default,relation.RelationActionRequest" json:"Request"`
}

func NewSocialServiceRelationActionArgs() *SocialServiceRelationActionArgs {
	return &SocialServiceRelationActionArgs{}
}

func (p *SocialServiceRelationActionArgs) InitDefault() {
}

var SocialServiceRelationActionArgs_Request_DEFAULT *relation.RelationActionRequest

func (p *SocialServiceRelationActionArgs) GetRequest() (v *relation.RelationActionRequest) {
	if !p.IsSetRequest() {
		return SocialServiceRelationActionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceRelationActionArgs) SetRequest(val *relation.RelationActionRequest) {
	p.Request = val
}

func (p *SocialServiceRelationActionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceRelationActionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceRelationActionArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceRelationActionArgs = map[int16]string{
	1: "Request",
}

type SocialServiceRelationActionResult struct {
	Success *relation.RelationActionResponse `thrift:"success,0,optional" frugal:"0,optional,relation.RelationActionResponse" json:"success,omitempty"`
}

func NewSocialServiceRelationActionResult() *SocialServiceRelationActionResult {
	return &SocialServiceRelationActionResult{}
}

func (p *SocialServiceRelationActionResult) InitDefault() {
}

var SocialServiceRelationActionResult_Success_DEFAULT *relation.RelationActionResponse

func (p *SocialServiceRelationActionResult) GetSuccess() (v *relation.RelationActionResponse) {
	if !p.IsSetSuccess() {
		return SocialServiceRelationActionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceRelationActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.RelationActionResponse)
}

func (p *SocialServiceRelationActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceRelationActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceRelationActionResult(%+v)", *p)
}

var fieldIDToName_SocialServiceRelationActionResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFollowListArgs struct {
	Request *relation.FollowListRequest `thrift:"Request,1" frugal:"1,default,relation.FollowListRequest" json:"Request"`
}

func NewSocialServiceGetFollowListArgs() *SocialServiceGetFollowListArgs {
	return &SocialServiceGetFollowListArgs{}
}

func (p *SocialServiceGetFollowListArgs) InitDefault() {
}

var SocialServiceGetFollowListArgs_Request_DEFAULT *relation.FollowListRequest

func (p *SocialServiceGetFollowListArgs) GetRequest() (v *relation.FollowListRequest) {
	if !p.IsSetRequest() {
		return SocialServiceGetFollowListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceGetFollowListArgs) SetRequest(val *relation.FollowListRequest) {
	p.Request = val
}

func (p *SocialServiceGetFollowListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceGetFollowListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowListArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowListArgs = map[int16]string{
	1: "Request",
}

type SocialServiceGetFollowListResult struct {
	Success *relation.FollowListResponse `thrift:"success,0,optional" frugal:"0,optional,relation.FollowListResponse" json:"success,omitempty"`
}

func NewSocialServiceGetFollowListResult() *SocialServiceGetFollowListResult {
	return &SocialServiceGetFollowListResult{}
}

func (p *SocialServiceGetFollowListResult) InitDefault() {
}

var SocialServiceGetFollowListResult_Success_DEFAULT *relation.FollowListResponse

func (p *SocialServiceGetFollowListResult) GetSuccess() (v *relation.FollowListResponse) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFollowListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetFollowListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.FollowListResponse)
}

func (p *SocialServiceGetFollowListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFollowListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowListResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowListResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFollowerListArgs struct {
	Request *relation.FollowerListRequest `thrift:"Request,1" frugal:"1,default,relation.FollowerListRequest" json:"Request"`
}

func NewSocialServiceGetFollowerListArgs() *SocialServiceGetFollowerListArgs {
	return &SocialServiceGetFollowerListArgs{}
}

func (p *SocialServiceGetFollowerListArgs) InitDefault() {
}

var SocialServiceGetFollowerListArgs_Request_DEFAULT *relation.FollowerListRequest

func (p *SocialServiceGetFollowerListArgs) GetRequest() (v *relation.FollowerListRequest) {
	if !p.IsSetRequest() {
		return SocialServiceGetFollowerListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceGetFollowerListArgs) SetRequest(val *relation.FollowerListRequest) {
	p.Request = val
}

func (p *SocialServiceGetFollowerListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceGetFollowerListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowerListArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowerListArgs = map[int16]string{
	1: "Request",
}

type SocialServiceGetFollowerListResult struct {
	Success *relation.FollowerListResponse `thrift:"success,0,optional" frugal:"0,optional,relation.FollowerListResponse" json:"success,omitempty"`
}

func NewSocialServiceGetFollowerListResult() *SocialServiceGetFollowerListResult {
	return &SocialServiceGetFollowerListResult{}
}

func (p *SocialServiceGetFollowerListResult) InitDefault() {
}

var SocialServiceGetFollowerListResult_Success_DEFAULT *relation.FollowerListResponse

func (p *SocialServiceGetFollowerListResult) GetSuccess() (v *relation.FollowerListResponse) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFollowerListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetFollowerListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.FollowerListResponse)
}

func (p *SocialServiceGetFollowerListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFollowerListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowerListResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowerListResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFriendListArgs struct {
	Request *relation.FriendListRequest `thrift:"Request,1" frugal:"1,default,relation.FriendListRequest" json:"Request"`
}

func NewSocialServiceGetFriendListArgs() *SocialServiceGetFriendListArgs {
	return &SocialServiceGetFriendListArgs{}
}

func (p *SocialServiceGetFriendListArgs) InitDefault() {
}

var SocialServiceGetFriendListArgs_Request_DEFAULT *relation.FriendListRequest

func (p *SocialServiceGetFriendListArgs) GetRequest() (v *relation.FriendListRequest) {
	if !p.IsSetRequest() {
		return SocialServiceGetFriendListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceGetFriendListArgs) SetRequest(val *relation.FriendListRequest) {
	p.Request = val
}

func (p *SocialServiceGetFriendListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceGetFriendListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFriendListArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFriendListArgs = map[int16]string{
	1: "Request",
}

type SocialServiceGetFriendListResult struct {
	Success *relation.FriendListResponse `thrift:"success,0,optional" frugal:"0,optional,relation.FriendListResponse" json:"success,omitempty"`
}

func NewSocialServiceGetFriendListResult() *SocialServiceGetFriendListResult {
	return &SocialServiceGetFriendListResult{}
}

func (p *SocialServiceGetFriendListResult) InitDefault() {
}

var SocialServiceGetFriendListResult_Success_DEFAULT *relation.FriendListResponse

func (p *SocialServiceGetFriendListResult) GetSuccess() (v *relation.FriendListResponse) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFriendListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetFriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.FriendListResponse)
}

func (p *SocialServiceGetFriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFriendListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFriendListResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFriendListResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFollowListCountArgs struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewSocialServiceGetFollowListCountArgs() *SocialServiceGetFollowListCountArgs {
	return &SocialServiceGetFollowListCountArgs{}
}

func (p *SocialServiceGetFollowListCountArgs) InitDefault() {
}

func (p *SocialServiceGetFollowListCountArgs) GetUserId() (v int64) {
	return p.UserId
}
func (p *SocialServiceGetFollowListCountArgs) SetUserId(val int64) {
	p.UserId = val
}

func (p *SocialServiceGetFollowListCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowListCountArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowListCountArgs = map[int16]string{
	1: "user_id",
}

type SocialServiceGetFollowListCountResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewSocialServiceGetFollowListCountResult() *SocialServiceGetFollowListCountResult {
	return &SocialServiceGetFollowListCountResult{}
}

func (p *SocialServiceGetFollowListCountResult) InitDefault() {
}

var SocialServiceGetFollowListCountResult_Success_DEFAULT int32

func (p *SocialServiceGetFollowListCountResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFollowListCountResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *SocialServiceGetFollowListCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *SocialServiceGetFollowListCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFollowListCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowListCountResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowListCountResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFollowerListCountArgs struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewSocialServiceGetFollowerListCountArgs() *SocialServiceGetFollowerListCountArgs {
	return &SocialServiceGetFollowerListCountArgs{}
}

func (p *SocialServiceGetFollowerListCountArgs) InitDefault() {
}

func (p *SocialServiceGetFollowerListCountArgs) GetUserId() (v int64) {
	return p.UserId
}
func (p *SocialServiceGetFollowerListCountArgs) SetUserId(val int64) {
	p.UserId = val
}

func (p *SocialServiceGetFollowerListCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowerListCountArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowerListCountArgs = map[int16]string{
	1: "user_id",
}

type SocialServiceGetFollowerListCountResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewSocialServiceGetFollowerListCountResult() *SocialServiceGetFollowerListCountResult {
	return &SocialServiceGetFollowerListCountResult{}
}

func (p *SocialServiceGetFollowerListCountResult) InitDefault() {
}

var SocialServiceGetFollowerListCountResult_Success_DEFAULT int32

func (p *SocialServiceGetFollowerListCountResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFollowerListCountResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *SocialServiceGetFollowerListCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *SocialServiceGetFollowerListCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFollowerListCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowerListCountResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowerListCountResult = map[int16]string{
	0: "success",
}

type SocialServiceIsFollowingArgs struct {
	Request *relation.IsFollowingRequest `thrift:"Request,1" frugal:"1,default,relation.IsFollowingRequest" json:"Request"`
}

func NewSocialServiceIsFollowingArgs() *SocialServiceIsFollowingArgs {
	return &SocialServiceIsFollowingArgs{}
}

func (p *SocialServiceIsFollowingArgs) InitDefault() {
}

var SocialServiceIsFollowingArgs_Request_DEFAULT *relation.IsFollowingRequest

func (p *SocialServiceIsFollowingArgs) GetRequest() (v *relation.IsFollowingRequest) {
	if !p.IsSetRequest() {
		return SocialServiceIsFollowingArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceIsFollowingArgs) SetRequest(val *relation.IsFollowingRequest) {
	p.Request = val
}

func (p *SocialServiceIsFollowingArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceIsFollowingArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceIsFollowingArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceIsFollowingArgs = map[int16]string{
	1: "Request",
}

type SocialServiceIsFollowingResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewSocialServiceIsFollowingResult() *SocialServiceIsFollowingResult {
	return &SocialServiceIsFollowingResult{}
}

func (p *SocialServiceIsFollowingResult) InitDefault() {
}

var SocialServiceIsFollowingResult_Success_DEFAULT bool

func (p *SocialServiceIsFollowingResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return SocialServiceIsFollowingResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *SocialServiceIsFollowingResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *SocialServiceIsFollowingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceIsFollowingResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceIsFollowingResult(%+v)", *p)
}

var fieldIDToName_SocialServiceIsFollowingResult = map[int16]string{
	0: "success",
}

type SocialServiceIsFriendArgs struct {
	Request *relation.IsFriendRequest `thrift:"Request,1" frugal:"1,default,relation.IsFriendRequest" json:"Request"`
}

func NewSocialServiceIsFriendArgs() *SocialServiceIsFriendArgs {
	return &SocialServiceIsFriendArgs{}
}

func (p *SocialServiceIsFriendArgs) InitDefault() {
}

var SocialServiceIsFriendArgs_Request_DEFAULT *relation.IsFriendRequest

func (p *SocialServiceIsFriendArgs) GetRequest() (v *relation.IsFriendRequest) {
	if !p.IsSetRequest() {
		return SocialServiceIsFriendArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *SocialServiceIsFriendArgs) SetRequest(val *relation.IsFriendRequest) {
	p.Request = val
}

func (p *SocialServiceIsFriendArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *SocialServiceIsFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceIsFriendArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceIsFriendArgs = map[int16]string{
	1: "Request",
}

type SocialServiceIsFriendResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewSocialServiceIsFriendResult() *SocialServiceIsFriendResult {
	return &SocialServiceIsFriendResult{}
}

func (p *SocialServiceIsFriendResult) InitDefault() {
}

var SocialServiceIsFriendResult_Success_DEFAULT bool

func (p *SocialServiceIsFriendResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return SocialServiceIsFriendResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *SocialServiceIsFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *SocialServiceIsFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceIsFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceIsFriendResult(%+v)", *p)
}

var fieldIDToName_SocialServiceIsFriendResult = map[int16]string{
	0: "success",
}
