// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package favorite

import (
	"douyin/kitex_gen/video"
	"fmt"
)

type FavoriteActionRequest struct {
	UserId     int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	VideoId    int64 `thrift:"video_id,2" frugal:"2,default,i64" json:"video_id"`
	ActionType int32 `thrift:"action_type,3" frugal:"3,default,i32" json:"action_type"`
}

func NewFavoriteActionRequest() *FavoriteActionRequest {
	return &FavoriteActionRequest{}
}

func (p *FavoriteActionRequest) InitDefault() {
}

func (p *FavoriteActionRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *FavoriteActionRequest) GetVideoId() (v int64) {
	return p.VideoId
}

func (p *FavoriteActionRequest) GetActionType() (v int32) {
	return p.ActionType
}
func (p *FavoriteActionRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *FavoriteActionRequest) SetVideoId(val int64) {
	p.VideoId = val
}
func (p *FavoriteActionRequest) SetActionType(val int32) {
	p.ActionType = val
}

func (p *FavoriteActionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FavoriteActionRequest(%+v)", *p)
}

var fieldIDToName_FavoriteActionRequest = map[int16]string{
	1: "user_id",
	2: "video_id",
	3: "action_type",
}

type FavoriteActionResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
}

func NewFavoriteActionResponse() *FavoriteActionResponse {
	return &FavoriteActionResponse{}
}

func (p *FavoriteActionResponse) InitDefault() {
}

func (p *FavoriteActionResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *FavoriteActionResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}
func (p *FavoriteActionResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *FavoriteActionResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}

func (p *FavoriteActionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FavoriteActionResponse(%+v)", *p)
}

var fieldIDToName_FavoriteActionResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
}

type FavoriteListRequest struct {
	ActionId int64 `thrift:"action_id,1" frugal:"1,default,i64" json:"action_id"`
	UserId   int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewFavoriteListRequest() *FavoriteListRequest {
	return &FavoriteListRequest{}
}

func (p *FavoriteListRequest) InitDefault() {
}

func (p *FavoriteListRequest) GetActionId() (v int64) {
	return p.ActionId
}

func (p *FavoriteListRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *FavoriteListRequest) SetActionId(val int64) {
	p.ActionId = val
}
func (p *FavoriteListRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *FavoriteListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FavoriteListRequest(%+v)", *p)
}

var fieldIDToName_FavoriteListRequest = map[int16]string{
	1: "action_id",
	2: "user_id",
}

type FavoriteListResponse struct {
	StatusCode int32          `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string         `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	VideoList  []*video.Video `thrift:"video_list,3" frugal:"3,default,list<video.Video>" json:"video_list"`
}

func NewFavoriteListResponse() *FavoriteListResponse {
	return &FavoriteListResponse{}
}

func (p *FavoriteListResponse) InitDefault() {
}

func (p *FavoriteListResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *FavoriteListResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *FavoriteListResponse) GetVideoList() (v []*video.Video) {
	return p.VideoList
}
func (p *FavoriteListResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *FavoriteListResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *FavoriteListResponse) SetVideoList(val []*video.Video) {
	p.VideoList = val
}

func (p *FavoriteListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FavoriteListResponse(%+v)", *p)
}

var fieldIDToName_FavoriteListResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "video_list",
}

type IsUserFavoriteRequest struct {
	UserId  int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	VideoId int64 `thrift:"video_id,2" frugal:"2,default,i64" json:"video_id"`
}

func NewIsUserFavoriteRequest() *IsUserFavoriteRequest {
	return &IsUserFavoriteRequest{}
}

func (p *IsUserFavoriteRequest) InitDefault() {
}

func (p *IsUserFavoriteRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *IsUserFavoriteRequest) GetVideoId() (v int64) {
	return p.VideoId
}
func (p *IsUserFavoriteRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *IsUserFavoriteRequest) SetVideoId(val int64) {
	p.VideoId = val
}

func (p *IsUserFavoriteRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IsUserFavoriteRequest(%+v)", *p)
}

var fieldIDToName_IsUserFavoriteRequest = map[int16]string{
	1: "user_id",
	2: "video_id",
}
