// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"fmt"
)

type User struct {
	Id              int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name            string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	FollowCount     int32  `thrift:"follow_count,3" frugal:"3,default,i32" json:"follow_count"`
	FollowerCount   int32  `thrift:"follower_count,4" frugal:"4,default,i32" json:"follower_count"`
	IsFollow        bool   `thrift:"is_follow,5" frugal:"5,default,bool" json:"is_follow"`
	Avatar          string `thrift:"avatar,6" frugal:"6,default,string" json:"avatar"`
	BackgroundImage string `thrift:"background_image,7" frugal:"7,default,string" json:"background_image"`
	Signature       string `thrift:"signature,8" frugal:"8,default,string" json:"signature"`
	TotalFavorited  string `thrift:"total_favorited,9" frugal:"9,default,string" json:"total_favorited"`
	WorkCount       int32  `thrift:"work_count,10" frugal:"10,default,i32" json:"work_count"`
	FavoriteCount   int32  `thrift:"favorite_count,11" frugal:"11,default,i32" json:"favorite_count"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetName() (v string) {
	return p.Name
}

func (p *User) GetFollowCount() (v int32) {
	return p.FollowCount
}

func (p *User) GetFollowerCount() (v int32) {
	return p.FollowerCount
}

func (p *User) GetIsFollow() (v bool) {
	return p.IsFollow
}

func (p *User) GetAvatar() (v string) {
	return p.Avatar
}

func (p *User) GetBackgroundImage() (v string) {
	return p.BackgroundImage
}

func (p *User) GetSignature() (v string) {
	return p.Signature
}

func (p *User) GetTotalFavorited() (v string) {
	return p.TotalFavorited
}

func (p *User) GetWorkCount() (v int32) {
	return p.WorkCount
}

func (p *User) GetFavoriteCount() (v int32) {
	return p.FavoriteCount
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetName(val string) {
	p.Name = val
}
func (p *User) SetFollowCount(val int32) {
	p.FollowCount = val
}
func (p *User) SetFollowerCount(val int32) {
	p.FollowerCount = val
}
func (p *User) SetIsFollow(val bool) {
	p.IsFollow = val
}
func (p *User) SetAvatar(val string) {
	p.Avatar = val
}
func (p *User) SetBackgroundImage(val string) {
	p.BackgroundImage = val
}
func (p *User) SetSignature(val string) {
	p.Signature = val
}
func (p *User) SetTotalFavorited(val string) {
	p.TotalFavorited = val
}
func (p *User) SetWorkCount(val int32) {
	p.WorkCount = val
}
func (p *User) SetFavoriteCount(val int32) {
	p.FavoriteCount = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "follow_count",
	4:  "follower_count",
	5:  "is_follow",
	6:  "avatar",
	7:  "background_image",
	8:  "signature",
	9:  "total_favorited",
	10: "work_count",
	11: "favorite_count",
}

type UserRegisterRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewUserRegisterRequest() *UserRegisterRequest {
	return &UserRegisterRequest{}
}

func (p *UserRegisterRequest) InitDefault() {
}

func (p *UserRegisterRequest) GetUsername() (v string) {
	return p.Username
}

func (p *UserRegisterRequest) GetPassword() (v string) {
	return p.Password
}
func (p *UserRegisterRequest) SetUsername(val string) {
	p.Username = val
}
func (p *UserRegisterRequest) SetPassword(val string) {
	p.Password = val
}

func (p *UserRegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserRegisterRequest(%+v)", *p)
}

var fieldIDToName_UserRegisterRequest = map[int16]string{
	1: "username",
	2: "password",
}

type UserRegisterResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	UserId     int64  `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	Token      string `thrift:"token,4" frugal:"4,default,string" json:"token"`
}

func NewUserRegisterResponse() *UserRegisterResponse {
	return &UserRegisterResponse{}
}

func (p *UserRegisterResponse) InitDefault() {
}

func (p *UserRegisterResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *UserRegisterResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *UserRegisterResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserRegisterResponse) GetToken() (v string) {
	return p.Token
}
func (p *UserRegisterResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *UserRegisterResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *UserRegisterResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserRegisterResponse) SetToken(val string) {
	p.Token = val
}

func (p *UserRegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserRegisterResponse(%+v)", *p)
}

var fieldIDToName_UserRegisterResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "user_id",
	4: "token",
}

type UserLoginRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewUserLoginRequest() *UserLoginRequest {
	return &UserLoginRequest{}
}

func (p *UserLoginRequest) InitDefault() {
}

func (p *UserLoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *UserLoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *UserLoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *UserLoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *UserLoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginRequest(%+v)", *p)
}

var fieldIDToName_UserLoginRequest = map[int16]string{
	1: "username",
	2: "password",
}

type UserLoginResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	UserId     int64  `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	Token      string `thrift:"token,4" frugal:"4,default,string" json:"token"`
}

func NewUserLoginResponse() *UserLoginResponse {
	return &UserLoginResponse{}
}

func (p *UserLoginResponse) InitDefault() {
}

func (p *UserLoginResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *UserLoginResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *UserLoginResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserLoginResponse) GetToken() (v string) {
	return p.Token
}
func (p *UserLoginResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *UserLoginResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *UserLoginResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserLoginResponse) SetToken(val string) {
	p.Token = val
}

func (p *UserLoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginResponse(%+v)", *p)
}

var fieldIDToName_UserLoginResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "user_id",
	4: "token",
}

type UserInfoByIdRequest struct {
	ActorId int64 `thrift:"actor_id,1" frugal:"1,default,i64" json:"actor_id"`
	UserId  int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewUserInfoByIdRequest() *UserInfoByIdRequest {
	return &UserInfoByIdRequest{}
}

func (p *UserInfoByIdRequest) InitDefault() {
}

func (p *UserInfoByIdRequest) GetActorId() (v int64) {
	return p.ActorId
}

func (p *UserInfoByIdRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *UserInfoByIdRequest) SetActorId(val int64) {
	p.ActorId = val
}
func (p *UserInfoByIdRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *UserInfoByIdRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoByIdRequest(%+v)", *p)
}

var fieldIDToName_UserInfoByIdRequest = map[int16]string{
	1: "actor_id",
	2: "user_id",
}

type UserInfoByIdResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	User       *User  `thrift:"user,3" frugal:"3,default,User" json:"user"`
}

func NewUserInfoByIdResponse() *UserInfoByIdResponse {
	return &UserInfoByIdResponse{}
}

func (p *UserInfoByIdResponse) InitDefault() {
}

func (p *UserInfoByIdResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *UserInfoByIdResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

var UserInfoByIdResponse_User_DEFAULT *User

func (p *UserInfoByIdResponse) GetUser() (v *User) {
	if !p.IsSetUser() {
		return UserInfoByIdResponse_User_DEFAULT
	}
	return p.User
}
func (p *UserInfoByIdResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *UserInfoByIdResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *UserInfoByIdResponse) SetUser(val *User) {
	p.User = val
}

func (p *UserInfoByIdResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *UserInfoByIdResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoByIdResponse(%+v)", *p)
}

var fieldIDToName_UserInfoByIdResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "user",
}

type UserInfoByNameRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
}

func NewUserInfoByNameRequest() *UserInfoByNameRequest {
	return &UserInfoByNameRequest{}
}

func (p *UserInfoByNameRequest) InitDefault() {
}

func (p *UserInfoByNameRequest) GetUsername() (v string) {
	return p.Username
}
func (p *UserInfoByNameRequest) SetUsername(val string) {
	p.Username = val
}

func (p *UserInfoByNameRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoByNameRequest(%+v)", *p)
}

var fieldIDToName_UserInfoByNameRequest = map[int16]string{
	1: "username",
}

type UserInfoByNameResponse struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
	UserId     int64  `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	Password   string `thrift:"password,4" frugal:"4,default,string" json:"password"`
}

func NewUserInfoByNameResponse() *UserInfoByNameResponse {
	return &UserInfoByNameResponse{}
}

func (p *UserInfoByNameResponse) InitDefault() {
}

func (p *UserInfoByNameResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *UserInfoByNameResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}

func (p *UserInfoByNameResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserInfoByNameResponse) GetPassword() (v string) {
	return p.Password
}
func (p *UserInfoByNameResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *UserInfoByNameResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}
func (p *UserInfoByNameResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserInfoByNameResponse) SetPassword(val string) {
	p.Password = val
}

func (p *UserInfoByNameResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoByNameResponse(%+v)", *p)
}

var fieldIDToName_UserInfoByNameResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
	3: "user_id",
	4: "password",
}

type UserExistsRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
}

func NewUserExistsRequest() *UserExistsRequest {
	return &UserExistsRequest{}
}

func (p *UserExistsRequest) InitDefault() {
}

func (p *UserExistsRequest) GetUsername() (v string) {
	return p.Username
}
func (p *UserExistsRequest) SetUsername(val string) {
	p.Username = val
}

func (p *UserExistsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserExistsRequest(%+v)", *p)
}

var fieldIDToName_UserExistsRequest = map[int16]string{
	1: "username",
}

type UserExistsResponse struct {
	Exist bool `thrift:"exist,1" frugal:"1,default,bool" json:"exist"`
}

func NewUserExistsResponse() *UserExistsResponse {
	return &UserExistsResponse{}
}

func (p *UserExistsResponse) InitDefault() {
}

func (p *UserExistsResponse) GetExist() (v bool) {
	return p.Exist
}
func (p *UserExistsResponse) SetExist(val bool) {
	p.Exist = val
}

func (p *UserExistsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserExistsResponse(%+v)", *p)
}

var fieldIDToName_UserExistsResponse = map[int16]string{
	1: "exist",
}
