// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package videoapp

import (
	"context"
	"douyin/kitex_gen/comment"
	"douyin/kitex_gen/favorite"
	"douyin/kitex_gen/video"
	"fmt"
)

type VideoAppService interface {
	VideoFeed(ctx context.Context, request *video.VideoFeedRequest) (r *video.VideoFeedResponse, err error)

	PublishVideo(ctx context.Context, request *video.PublishVideoRequest) (r *video.PublishVideoResponse, err error)

	GetPublishVideoList(ctx context.Context, request *video.PublishVideoListRequest) (r *video.PublishVideoListResponse, err error)

	GetWorkCount(ctx context.Context, userId int64) (r int32, err error)

	CommentAction(ctx context.Context, request *comment.CommentActionRequest) (r *comment.CommentActionResponse, err error)

	GetCommentList(ctx context.Context, request *comment.CommentListRequest) (r *comment.CommentListResponse, err error)

	GetCommentCount(ctx context.Context, videoId int64) (r int32, err error)

	FavoriteAction(ctx context.Context, request *favorite.FavoriteActionRequest) (r *favorite.FavoriteActionResponse, err error)

	GetFavoriteList(ctx context.Context, request *favorite.FavoriteListRequest) (r *favorite.FavoriteListResponse, err error)

	GetVideoFavoriteCount(ctx context.Context, videoId int64) (r int32, err error)

	GetUserFavoriteCount(ctx context.Context, userId int64) (r int32, err error)

	GetUserTotalFavoritedCount(ctx context.Context, userId int64) (r int32, err error)

	IsUserFavorite(ctx context.Context, request *favorite.IsUserFavoriteRequest) (r bool, err error)
}

type VideoAppServiceVideoFeedArgs struct {
	Request *video.VideoFeedRequest `thrift:"Request,1" frugal:"1,default,video.VideoFeedRequest" json:"Request"`
}

func NewVideoAppServiceVideoFeedArgs() *VideoAppServiceVideoFeedArgs {
	return &VideoAppServiceVideoFeedArgs{}
}

func (p *VideoAppServiceVideoFeedArgs) InitDefault() {
}

var VideoAppServiceVideoFeedArgs_Request_DEFAULT *video.VideoFeedRequest

func (p *VideoAppServiceVideoFeedArgs) GetRequest() (v *video.VideoFeedRequest) {
	if !p.IsSetRequest() {
		return VideoAppServiceVideoFeedArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServiceVideoFeedArgs) SetRequest(val *video.VideoFeedRequest) {
	p.Request = val
}

func (p *VideoAppServiceVideoFeedArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServiceVideoFeedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceVideoFeedArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceVideoFeedArgs = map[int16]string{
	1: "Request",
}

type VideoAppServiceVideoFeedResult struct {
	Success *video.VideoFeedResponse `thrift:"success,0,optional" frugal:"0,optional,video.VideoFeedResponse" json:"success,omitempty"`
}

func NewVideoAppServiceVideoFeedResult() *VideoAppServiceVideoFeedResult {
	return &VideoAppServiceVideoFeedResult{}
}

func (p *VideoAppServiceVideoFeedResult) InitDefault() {
}

var VideoAppServiceVideoFeedResult_Success_DEFAULT *video.VideoFeedResponse

func (p *VideoAppServiceVideoFeedResult) GetSuccess() (v *video.VideoFeedResponse) {
	if !p.IsSetSuccess() {
		return VideoAppServiceVideoFeedResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoAppServiceVideoFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.VideoFeedResponse)
}

func (p *VideoAppServiceVideoFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceVideoFeedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceVideoFeedResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceVideoFeedResult = map[int16]string{
	0: "success",
}

type VideoAppServicePublishVideoArgs struct {
	Request *video.PublishVideoRequest `thrift:"Request,1" frugal:"1,default,video.PublishVideoRequest" json:"Request"`
}

func NewVideoAppServicePublishVideoArgs() *VideoAppServicePublishVideoArgs {
	return &VideoAppServicePublishVideoArgs{}
}

func (p *VideoAppServicePublishVideoArgs) InitDefault() {
}

var VideoAppServicePublishVideoArgs_Request_DEFAULT *video.PublishVideoRequest

func (p *VideoAppServicePublishVideoArgs) GetRequest() (v *video.PublishVideoRequest) {
	if !p.IsSetRequest() {
		return VideoAppServicePublishVideoArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServicePublishVideoArgs) SetRequest(val *video.PublishVideoRequest) {
	p.Request = val
}

func (p *VideoAppServicePublishVideoArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServicePublishVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServicePublishVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServicePublishVideoArgs = map[int16]string{
	1: "Request",
}

type VideoAppServicePublishVideoResult struct {
	Success *video.PublishVideoResponse `thrift:"success,0,optional" frugal:"0,optional,video.PublishVideoResponse" json:"success,omitempty"`
}

func NewVideoAppServicePublishVideoResult() *VideoAppServicePublishVideoResult {
	return &VideoAppServicePublishVideoResult{}
}

func (p *VideoAppServicePublishVideoResult) InitDefault() {
}

var VideoAppServicePublishVideoResult_Success_DEFAULT *video.PublishVideoResponse

func (p *VideoAppServicePublishVideoResult) GetSuccess() (v *video.PublishVideoResponse) {
	if !p.IsSetSuccess() {
		return VideoAppServicePublishVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoAppServicePublishVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.PublishVideoResponse)
}

func (p *VideoAppServicePublishVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServicePublishVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServicePublishVideoResult(%+v)", *p)
}

var fieldIDToName_VideoAppServicePublishVideoResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetPublishVideoListArgs struct {
	Request *video.PublishVideoListRequest `thrift:"Request,1" frugal:"1,default,video.PublishVideoListRequest" json:"Request"`
}

func NewVideoAppServiceGetPublishVideoListArgs() *VideoAppServiceGetPublishVideoListArgs {
	return &VideoAppServiceGetPublishVideoListArgs{}
}

func (p *VideoAppServiceGetPublishVideoListArgs) InitDefault() {
}

var VideoAppServiceGetPublishVideoListArgs_Request_DEFAULT *video.PublishVideoListRequest

func (p *VideoAppServiceGetPublishVideoListArgs) GetRequest() (v *video.PublishVideoListRequest) {
	if !p.IsSetRequest() {
		return VideoAppServiceGetPublishVideoListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServiceGetPublishVideoListArgs) SetRequest(val *video.PublishVideoListRequest) {
	p.Request = val
}

func (p *VideoAppServiceGetPublishVideoListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServiceGetPublishVideoListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetPublishVideoListArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetPublishVideoListArgs = map[int16]string{
	1: "Request",
}

type VideoAppServiceGetPublishVideoListResult struct {
	Success *video.PublishVideoListResponse `thrift:"success,0,optional" frugal:"0,optional,video.PublishVideoListResponse" json:"success,omitempty"`
}

func NewVideoAppServiceGetPublishVideoListResult() *VideoAppServiceGetPublishVideoListResult {
	return &VideoAppServiceGetPublishVideoListResult{}
}

func (p *VideoAppServiceGetPublishVideoListResult) InitDefault() {
}

var VideoAppServiceGetPublishVideoListResult_Success_DEFAULT *video.PublishVideoListResponse

func (p *VideoAppServiceGetPublishVideoListResult) GetSuccess() (v *video.PublishVideoListResponse) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetPublishVideoListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoAppServiceGetPublishVideoListResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.PublishVideoListResponse)
}

func (p *VideoAppServiceGetPublishVideoListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetPublishVideoListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetPublishVideoListResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetPublishVideoListResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetWorkCountArgs struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewVideoAppServiceGetWorkCountArgs() *VideoAppServiceGetWorkCountArgs {
	return &VideoAppServiceGetWorkCountArgs{}
}

func (p *VideoAppServiceGetWorkCountArgs) InitDefault() {
}

func (p *VideoAppServiceGetWorkCountArgs) GetUserId() (v int64) {
	return p.UserId
}
func (p *VideoAppServiceGetWorkCountArgs) SetUserId(val int64) {
	p.UserId = val
}

func (p *VideoAppServiceGetWorkCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetWorkCountArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetWorkCountArgs = map[int16]string{
	1: "user_id",
}

type VideoAppServiceGetWorkCountResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewVideoAppServiceGetWorkCountResult() *VideoAppServiceGetWorkCountResult {
	return &VideoAppServiceGetWorkCountResult{}
}

func (p *VideoAppServiceGetWorkCountResult) InitDefault() {
}

var VideoAppServiceGetWorkCountResult_Success_DEFAULT int32

func (p *VideoAppServiceGetWorkCountResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetWorkCountResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VideoAppServiceGetWorkCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *VideoAppServiceGetWorkCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetWorkCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetWorkCountResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetWorkCountResult = map[int16]string{
	0: "success",
}

type VideoAppServiceCommentActionArgs struct {
	Request *comment.CommentActionRequest `thrift:"Request,1" frugal:"1,default,comment.CommentActionRequest" json:"Request"`
}

func NewVideoAppServiceCommentActionArgs() *VideoAppServiceCommentActionArgs {
	return &VideoAppServiceCommentActionArgs{}
}

func (p *VideoAppServiceCommentActionArgs) InitDefault() {
}

var VideoAppServiceCommentActionArgs_Request_DEFAULT *comment.CommentActionRequest

func (p *VideoAppServiceCommentActionArgs) GetRequest() (v *comment.CommentActionRequest) {
	if !p.IsSetRequest() {
		return VideoAppServiceCommentActionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServiceCommentActionArgs) SetRequest(val *comment.CommentActionRequest) {
	p.Request = val
}

func (p *VideoAppServiceCommentActionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServiceCommentActionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceCommentActionArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceCommentActionArgs = map[int16]string{
	1: "Request",
}

type VideoAppServiceCommentActionResult struct {
	Success *comment.CommentActionResponse `thrift:"success,0,optional" frugal:"0,optional,comment.CommentActionResponse" json:"success,omitempty"`
}

func NewVideoAppServiceCommentActionResult() *VideoAppServiceCommentActionResult {
	return &VideoAppServiceCommentActionResult{}
}

func (p *VideoAppServiceCommentActionResult) InitDefault() {
}

var VideoAppServiceCommentActionResult_Success_DEFAULT *comment.CommentActionResponse

func (p *VideoAppServiceCommentActionResult) GetSuccess() (v *comment.CommentActionResponse) {
	if !p.IsSetSuccess() {
		return VideoAppServiceCommentActionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoAppServiceCommentActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*comment.CommentActionResponse)
}

func (p *VideoAppServiceCommentActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceCommentActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceCommentActionResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceCommentActionResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetCommentListArgs struct {
	Request *comment.CommentListRequest `thrift:"Request,1" frugal:"1,default,comment.CommentListRequest" json:"Request"`
}

func NewVideoAppServiceGetCommentListArgs() *VideoAppServiceGetCommentListArgs {
	return &VideoAppServiceGetCommentListArgs{}
}

func (p *VideoAppServiceGetCommentListArgs) InitDefault() {
}

var VideoAppServiceGetCommentListArgs_Request_DEFAULT *comment.CommentListRequest

func (p *VideoAppServiceGetCommentListArgs) GetRequest() (v *comment.CommentListRequest) {
	if !p.IsSetRequest() {
		return VideoAppServiceGetCommentListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServiceGetCommentListArgs) SetRequest(val *comment.CommentListRequest) {
	p.Request = val
}

func (p *VideoAppServiceGetCommentListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServiceGetCommentListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetCommentListArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetCommentListArgs = map[int16]string{
	1: "Request",
}

type VideoAppServiceGetCommentListResult struct {
	Success *comment.CommentListResponse `thrift:"success,0,optional" frugal:"0,optional,comment.CommentListResponse" json:"success,omitempty"`
}

func NewVideoAppServiceGetCommentListResult() *VideoAppServiceGetCommentListResult {
	return &VideoAppServiceGetCommentListResult{}
}

func (p *VideoAppServiceGetCommentListResult) InitDefault() {
}

var VideoAppServiceGetCommentListResult_Success_DEFAULT *comment.CommentListResponse

func (p *VideoAppServiceGetCommentListResult) GetSuccess() (v *comment.CommentListResponse) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetCommentListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoAppServiceGetCommentListResult) SetSuccess(x interface{}) {
	p.Success = x.(*comment.CommentListResponse)
}

func (p *VideoAppServiceGetCommentListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetCommentListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetCommentListResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetCommentListResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetCommentCountArgs struct {
	VideoId int64 `thrift:"video_id,1" frugal:"1,default,i64" json:"video_id"`
}

func NewVideoAppServiceGetCommentCountArgs() *VideoAppServiceGetCommentCountArgs {
	return &VideoAppServiceGetCommentCountArgs{}
}

func (p *VideoAppServiceGetCommentCountArgs) InitDefault() {
}

func (p *VideoAppServiceGetCommentCountArgs) GetVideoId() (v int64) {
	return p.VideoId
}
func (p *VideoAppServiceGetCommentCountArgs) SetVideoId(val int64) {
	p.VideoId = val
}

func (p *VideoAppServiceGetCommentCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetCommentCountArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetCommentCountArgs = map[int16]string{
	1: "video_id",
}

type VideoAppServiceGetCommentCountResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewVideoAppServiceGetCommentCountResult() *VideoAppServiceGetCommentCountResult {
	return &VideoAppServiceGetCommentCountResult{}
}

func (p *VideoAppServiceGetCommentCountResult) InitDefault() {
}

var VideoAppServiceGetCommentCountResult_Success_DEFAULT int32

func (p *VideoAppServiceGetCommentCountResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetCommentCountResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VideoAppServiceGetCommentCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *VideoAppServiceGetCommentCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetCommentCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetCommentCountResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetCommentCountResult = map[int16]string{
	0: "success",
}

type VideoAppServiceFavoriteActionArgs struct {
	Request *favorite.FavoriteActionRequest `thrift:"Request,1" frugal:"1,default,favorite.FavoriteActionRequest" json:"Request"`
}

func NewVideoAppServiceFavoriteActionArgs() *VideoAppServiceFavoriteActionArgs {
	return &VideoAppServiceFavoriteActionArgs{}
}

func (p *VideoAppServiceFavoriteActionArgs) InitDefault() {
}

var VideoAppServiceFavoriteActionArgs_Request_DEFAULT *favorite.FavoriteActionRequest

func (p *VideoAppServiceFavoriteActionArgs) GetRequest() (v *favorite.FavoriteActionRequest) {
	if !p.IsSetRequest() {
		return VideoAppServiceFavoriteActionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServiceFavoriteActionArgs) SetRequest(val *favorite.FavoriteActionRequest) {
	p.Request = val
}

func (p *VideoAppServiceFavoriteActionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServiceFavoriteActionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceFavoriteActionArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceFavoriteActionArgs = map[int16]string{
	1: "Request",
}

type VideoAppServiceFavoriteActionResult struct {
	Success *favorite.FavoriteActionResponse `thrift:"success,0,optional" frugal:"0,optional,favorite.FavoriteActionResponse" json:"success,omitempty"`
}

func NewVideoAppServiceFavoriteActionResult() *VideoAppServiceFavoriteActionResult {
	return &VideoAppServiceFavoriteActionResult{}
}

func (p *VideoAppServiceFavoriteActionResult) InitDefault() {
}

var VideoAppServiceFavoriteActionResult_Success_DEFAULT *favorite.FavoriteActionResponse

func (p *VideoAppServiceFavoriteActionResult) GetSuccess() (v *favorite.FavoriteActionResponse) {
	if !p.IsSetSuccess() {
		return VideoAppServiceFavoriteActionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoAppServiceFavoriteActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*favorite.FavoriteActionResponse)
}

func (p *VideoAppServiceFavoriteActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceFavoriteActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceFavoriteActionResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceFavoriteActionResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetFavoriteListArgs struct {
	Request *favorite.FavoriteListRequest `thrift:"Request,1" frugal:"1,default,favorite.FavoriteListRequest" json:"Request"`
}

func NewVideoAppServiceGetFavoriteListArgs() *VideoAppServiceGetFavoriteListArgs {
	return &VideoAppServiceGetFavoriteListArgs{}
}

func (p *VideoAppServiceGetFavoriteListArgs) InitDefault() {
}

var VideoAppServiceGetFavoriteListArgs_Request_DEFAULT *favorite.FavoriteListRequest

func (p *VideoAppServiceGetFavoriteListArgs) GetRequest() (v *favorite.FavoriteListRequest) {
	if !p.IsSetRequest() {
		return VideoAppServiceGetFavoriteListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServiceGetFavoriteListArgs) SetRequest(val *favorite.FavoriteListRequest) {
	p.Request = val
}

func (p *VideoAppServiceGetFavoriteListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServiceGetFavoriteListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetFavoriteListArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetFavoriteListArgs = map[int16]string{
	1: "Request",
}

type VideoAppServiceGetFavoriteListResult struct {
	Success *favorite.FavoriteListResponse `thrift:"success,0,optional" frugal:"0,optional,favorite.FavoriteListResponse" json:"success,omitempty"`
}

func NewVideoAppServiceGetFavoriteListResult() *VideoAppServiceGetFavoriteListResult {
	return &VideoAppServiceGetFavoriteListResult{}
}

func (p *VideoAppServiceGetFavoriteListResult) InitDefault() {
}

var VideoAppServiceGetFavoriteListResult_Success_DEFAULT *favorite.FavoriteListResponse

func (p *VideoAppServiceGetFavoriteListResult) GetSuccess() (v *favorite.FavoriteListResponse) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetFavoriteListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoAppServiceGetFavoriteListResult) SetSuccess(x interface{}) {
	p.Success = x.(*favorite.FavoriteListResponse)
}

func (p *VideoAppServiceGetFavoriteListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetFavoriteListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetFavoriteListResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetFavoriteListResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetVideoFavoriteCountArgs struct {
	VideoId int64 `thrift:"video_id,1" frugal:"1,default,i64" json:"video_id"`
}

func NewVideoAppServiceGetVideoFavoriteCountArgs() *VideoAppServiceGetVideoFavoriteCountArgs {
	return &VideoAppServiceGetVideoFavoriteCountArgs{}
}

func (p *VideoAppServiceGetVideoFavoriteCountArgs) InitDefault() {
}

func (p *VideoAppServiceGetVideoFavoriteCountArgs) GetVideoId() (v int64) {
	return p.VideoId
}
func (p *VideoAppServiceGetVideoFavoriteCountArgs) SetVideoId(val int64) {
	p.VideoId = val
}

func (p *VideoAppServiceGetVideoFavoriteCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetVideoFavoriteCountArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetVideoFavoriteCountArgs = map[int16]string{
	1: "video_id",
}

type VideoAppServiceGetVideoFavoriteCountResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewVideoAppServiceGetVideoFavoriteCountResult() *VideoAppServiceGetVideoFavoriteCountResult {
	return &VideoAppServiceGetVideoFavoriteCountResult{}
}

func (p *VideoAppServiceGetVideoFavoriteCountResult) InitDefault() {
}

var VideoAppServiceGetVideoFavoriteCountResult_Success_DEFAULT int32

func (p *VideoAppServiceGetVideoFavoriteCountResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetVideoFavoriteCountResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VideoAppServiceGetVideoFavoriteCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *VideoAppServiceGetVideoFavoriteCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetVideoFavoriteCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetVideoFavoriteCountResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetVideoFavoriteCountResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetUserFavoriteCountArgs struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewVideoAppServiceGetUserFavoriteCountArgs() *VideoAppServiceGetUserFavoriteCountArgs {
	return &VideoAppServiceGetUserFavoriteCountArgs{}
}

func (p *VideoAppServiceGetUserFavoriteCountArgs) InitDefault() {
}

func (p *VideoAppServiceGetUserFavoriteCountArgs) GetUserId() (v int64) {
	return p.UserId
}
func (p *VideoAppServiceGetUserFavoriteCountArgs) SetUserId(val int64) {
	p.UserId = val
}

func (p *VideoAppServiceGetUserFavoriteCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetUserFavoriteCountArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetUserFavoriteCountArgs = map[int16]string{
	1: "user_id",
}

type VideoAppServiceGetUserFavoriteCountResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewVideoAppServiceGetUserFavoriteCountResult() *VideoAppServiceGetUserFavoriteCountResult {
	return &VideoAppServiceGetUserFavoriteCountResult{}
}

func (p *VideoAppServiceGetUserFavoriteCountResult) InitDefault() {
}

var VideoAppServiceGetUserFavoriteCountResult_Success_DEFAULT int32

func (p *VideoAppServiceGetUserFavoriteCountResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetUserFavoriteCountResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VideoAppServiceGetUserFavoriteCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *VideoAppServiceGetUserFavoriteCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetUserFavoriteCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetUserFavoriteCountResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetUserFavoriteCountResult = map[int16]string{
	0: "success",
}

type VideoAppServiceGetUserTotalFavoritedCountArgs struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewVideoAppServiceGetUserTotalFavoritedCountArgs() *VideoAppServiceGetUserTotalFavoritedCountArgs {
	return &VideoAppServiceGetUserTotalFavoritedCountArgs{}
}

func (p *VideoAppServiceGetUserTotalFavoritedCountArgs) InitDefault() {
}

func (p *VideoAppServiceGetUserTotalFavoritedCountArgs) GetUserId() (v int64) {
	return p.UserId
}
func (p *VideoAppServiceGetUserTotalFavoritedCountArgs) SetUserId(val int64) {
	p.UserId = val
}

func (p *VideoAppServiceGetUserTotalFavoritedCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetUserTotalFavoritedCountArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetUserTotalFavoritedCountArgs = map[int16]string{
	1: "user_id",
}

type VideoAppServiceGetUserTotalFavoritedCountResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewVideoAppServiceGetUserTotalFavoritedCountResult() *VideoAppServiceGetUserTotalFavoritedCountResult {
	return &VideoAppServiceGetUserTotalFavoritedCountResult{}
}

func (p *VideoAppServiceGetUserTotalFavoritedCountResult) InitDefault() {
}

var VideoAppServiceGetUserTotalFavoritedCountResult_Success_DEFAULT int32

func (p *VideoAppServiceGetUserTotalFavoritedCountResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return VideoAppServiceGetUserTotalFavoritedCountResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VideoAppServiceGetUserTotalFavoritedCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *VideoAppServiceGetUserTotalFavoritedCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceGetUserTotalFavoritedCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceGetUserTotalFavoritedCountResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceGetUserTotalFavoritedCountResult = map[int16]string{
	0: "success",
}

type VideoAppServiceIsUserFavoriteArgs struct {
	Request *favorite.IsUserFavoriteRequest `thrift:"Request,1" frugal:"1,default,favorite.IsUserFavoriteRequest" json:"Request"`
}

func NewVideoAppServiceIsUserFavoriteArgs() *VideoAppServiceIsUserFavoriteArgs {
	return &VideoAppServiceIsUserFavoriteArgs{}
}

func (p *VideoAppServiceIsUserFavoriteArgs) InitDefault() {
}

var VideoAppServiceIsUserFavoriteArgs_Request_DEFAULT *favorite.IsUserFavoriteRequest

func (p *VideoAppServiceIsUserFavoriteArgs) GetRequest() (v *favorite.IsUserFavoriteRequest) {
	if !p.IsSetRequest() {
		return VideoAppServiceIsUserFavoriteArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *VideoAppServiceIsUserFavoriteArgs) SetRequest(val *favorite.IsUserFavoriteRequest) {
	p.Request = val
}

func (p *VideoAppServiceIsUserFavoriteArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VideoAppServiceIsUserFavoriteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceIsUserFavoriteArgs(%+v)", *p)
}

var fieldIDToName_VideoAppServiceIsUserFavoriteArgs = map[int16]string{
	1: "Request",
}

type VideoAppServiceIsUserFavoriteResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewVideoAppServiceIsUserFavoriteResult() *VideoAppServiceIsUserFavoriteResult {
	return &VideoAppServiceIsUserFavoriteResult{}
}

func (p *VideoAppServiceIsUserFavoriteResult) InitDefault() {
}

var VideoAppServiceIsUserFavoriteResult_Success_DEFAULT bool

func (p *VideoAppServiceIsUserFavoriteResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return VideoAppServiceIsUserFavoriteResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VideoAppServiceIsUserFavoriteResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *VideoAppServiceIsUserFavoriteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoAppServiceIsUserFavoriteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoAppServiceIsUserFavoriteResult(%+v)", *p)
}

var fieldIDToName_VideoAppServiceIsUserFavoriteResult = map[int16]string{
	0: "success",
}
